### ISSUE TITLE
Some links are treated as link-less text when viewed on Firefox Quantum 

### ISSUE THREAD

**Issue by dbeezt** [Kong/docs.konghq.com#1006]
- `docs.konghq.com` url(s):
https://docs.konghq.com/

### Summary

Firefox Quantum has caused a strange array of bugs across a multitude of modern websites. The latest I've noticed is some kind of conflict between Quantum and whatever templating engine has been used to generate the Konghq web pages. The actual issue is that a majority of the links on the home page cease to function as links, instead operating as styled text. 

What's strange is that there is no syntactical error, as the links work perfectly fine on other browsers (tested IE11). I suspect that the non-working link-containing span elements are being generated in an incorrect order as when you (attempt to) drag-and-select the broken links, it forces selection/highlighting of the below div's heading element.

**NB:** This error only occurs when viewing the page in a double-column layout e.g. 1920x1080.

### Steps To Reproduce

1. Download Firefox Quantum
2. Open "https://docs.konghq.com/" using Firefox Quantum
3. Resize the window to a high-enough resolution that supports double-column layout of links
3. Click on "Install Kong ->"
4. Click on "Read the Proxy Reference ->" to compare

![error](https://user-images.githubusercontent.com/10518422/47752386-3525c500-dc8c-11e8-8038-fbcf71893980.gif)

**Comment by lena-larionova** [comment]
No longer an issue with newer browser versions.
