### ISSUE TITLE
Overlapping email form on /install pages

### ISSUE THREAD

**Issue by coopr** [Kong/docs.konghq.com#1020]
Pages like https://docs.konghq.com/install/google-cloud/ have this problem:

![install_-_google_cloud____kong_-_open-source_api_management_and_microservice_management](https://user-images.githubusercontent.com/94904/47925618-e2aafb00-de7b-11e8-9619-b35e8008a657.jpg)

**Comment by vyaspranjal33** [comment]
@coopr i would like to work on ,can u please share where this file will be located

**Comment by vyaspranjal33** [comment]
@coopr this is issue will be solved in #1022

**Comment by levfishbluefish** [comment]
Still seeing this issue
