### ISSUE TITLE
Ruby and Python versions might need updating in README

### ISSUE THREAD

**Issue by coopr** [Kong/docs.konghq.com#1030]
https://github.com/Kong/docs.konghq.com#prerequisites likely needs an update to correctly specify the acceptable Ruby and Python versions.

**Comment by vyaspranjal33** [comment]
@coopr should i update them to to stable version of those e.g python & ruby

**Comment by falondarville** [comment]
We created a task to update the README. DOCU-1570

**Comment by falondarville** [comment]
Run instructions with version details have been made current.
