### ISSUE TITLE
Some anchor links scroll to the wrong place

### ISSUE THREAD

**Issue by coopr** [Kong/docs.konghq.com#1039]
Visit https://docs.konghq.com/0.13.x/lua-reference/modules/kong.tools.responses/#send - notice how the "Send" anchor you are looking for is hidden under the page header and you have to scroll a little to see it.

**Comment by dagolinuxoid** [comment]
Yes it's kind of buggy - sometimes the url with `#send` at the end redirected me at the very top of the the page as if `#send` doesn't have an effect whatsoever, sometimes it behaves as you've mentioned above which is also a bummer :)

**Comment by dagolinuxoid** [comment]
Same thing with all hashes #status_codes, #Functions etc.

**Comment by dagolinuxoid** [comment]
Actually I know why this is happening. There is a div block with a class `navbar` which overlaps/hides the content since loading URL with appended #send will place the corresponding link relative to viewport. It's easy to notice by setting .navbar{display: none;}

**Comment by dagolinuxoid** [comment]
It happens when wide of browser is more than 1100pixels.

**Comment by levfishbluefish** [comment]
@h3xar0n are you still seeing this somewhere?

**Comment by h3xar0n** [comment]
@levfishbluefish I noticed it on Firefox, and @subnetmarco just saw it on Chrome for https://docs.konghq.com/1.0.x/configuration/#dns_stale_ttl (I cannot replicate it in Chrome, but have seen it elsewhere.) I happened to me when scrolling from navigation--not when visiting the link in a new window.

**Comment by subnetmarco** [comment]
I confirm that I still have this problem.

**Comment by Aswinpookkatt** [comment]
Could you describe the issue?
