### ISSUE TITLE
Reformat page header

### ISSUE THREAD

**Issue by h3xar0n** [Kong/docs.konghq.com#1059]
### Summary

As @coopr pointed out, the page header could use some reformatting.  

![48802218-6dd12100-ecc3-11e8-8dc9-6d7a8d109c96](https://user-images.githubusercontent.com/21048592/48860648-57d06880-ed76-11e8-98e8-7d9e16fd3cb7.jpg)

### Additional Details

Ensure that both Kong and Kong Enterprise headers are aligned.

**Comment by levfishbluefish** [comment]
Moving to internal ticket board
