### ISSUE TITLE
Command is not proper in ratelimit blog post

### ISSUE THREAD

**Issue by jogendrajangid1** [Kong/docs.konghq.com#1077]
https://konghq.com/blog/protecting-rate-limiting-api-kong/

The command is not correct in the blog post. It should be consumer based limit not API based.

Our consumer’s ID is “03040614-5cfb-4138-8277-c3f856de1fe8”, so we can now add a customized the Rate-Limiting plugin just for him, with a higher limit of 200 requests per minute:

curl http://127.0.0.1:8001/apis/mockbin/plugins/ \
     -d "name=rate-limiting" \
     -d "config.minute=200"
The above command will allow our consumer “mike” to make up to 200 requests per minute before being blocked by Kong, while still keeping the limit at 10req/minute for every other consumer.

**Comment by falondarville** [comment]
Since the referenced blog post has been published, the API endpoint in question has been deprecated. Please refer to current documentation: https://docs.konghq.com/hub/kong-inc/rate-limiting/
