### ISSUE TITLE
0.34 Enterprise docs missing "Managing Admins" page

### ISSUE THREAD

**Issue by millermatt** [Kong/docs.konghq.com#1110]
- `docs.konghq.com` url(s): https://docs.konghq.com/enterprise/0.34-x/kong-manager/overview/

### Summary

Managing Admins link leads to 404

### Steps To Reproduce

1. Go to https://docs.konghq.com/enterprise/0.34-x/kong-manager/overview/
2. Click "Managing Admins"
3. 404

**Comment by h3xar0n** [comment]
Thank you for raising this issue, @millermatt . We will fix the links. In the meantime, you can find the page for Managing Admins [here](https://docs.konghq.com/enterprise/0.34-x/kong-manager/organization-management/managing-admins/), and access any of the other pages from the side menu.
 
<img width="230" alt="screen shot 2019-01-14 at 5 29 55 pm" src="https://user-images.githubusercontent.com/21048592/51152773-1e6e2380-1822-11e9-80bb-d4a75e03a1e1.png">
