### ISSUE TITLE
Kong HUB pages do not have links for headers

### ISSUE THREAD

**Issue by Tieske** [Kong/docs.konghq.com#1117]
For support uses I want to link to the header "Template as Value" on this page: https://docs.konghq.com/hub/kong-inc/request-transformer-advanced/. But It doesn't have a link, so I can only link to the (top of the) page.

**Comment by h3xar0n** [comment]
@Tieske we'll keep the issue open; in the meantime, manually appending `#template-as-value` to the path will create a link to that part of the page since each header element has an ID:

https://docs.konghq.com/hub/kong-inc/request-transformer-advanced/#template-as-value

**Comment by Tieske** [comment]
@h3xar0n thx for the workaround, should have tried that myself 👍

**Comment by h3xar0n** [comment]
@Tieske, #1109 fixes this issue; it will go live in the next deployment this week.
