### ISSUE TITLE
Documentation for Kong PDK v1.0 not updated 

### ISSUE THREAD

**Issue by radudd** [Kong/docs.konghq.com#1132]
- `https://docs.konghq.com/1.0.x/plugin-development/admin-api/`
- `https://docs.konghq.com/1.0.x/plugin-development/custom-entities/`

### Summary

Old DAO has been removed in Kong 1.0 -  https://github.com/Kong/kong/blob/master/CHANGELOG.md#100, but the documentation still mentioned to use it.
>The old DAO implementation is removed, along with the old schema validation library (apis was the last entity using it). Use the new schema format instead in custom plugins. To ease the transition of plugins, the plugin loader in 1.0 includes a best-effort schema auto-translator, which should be sufficient for many plugins.

https://docs.konghq.com/1.0.x/plugin-development/custom-entities/

Same issue also about the extension of the Admin API documentation:
>The kong.api.crud_helpers module was removed (deprecated since the introduction of the new DAO in 0.13.0). Use kong.api.endpoints instead if you need to customize the auto-generated endpoints.

But the documentation still points to use `crud_helpers`
https://docs.konghq.com/1.0.x/plugin-development/admin-api/

### Steps To Reproduce

1. Trying to migrate a custom plugin from Kong 0.14 to Kong 1.0 
2. Documentation is not updated with the new breaking changes added in Kong 1.0, instead still points to use the old API resources

**Comment by subnetmarco** [comment]
@thibaultcha any updates on this?

**Comment by thibaultcha** [comment]
@subnetmarco Followed up privately

**Comment by falondarville** [comment]
Documentation for PDX v 1.0 is no longer being maintained. As of now, the most current version is available here: 
* https://docs.konghq.com/gateway-oss/2.4.x/plugin-development/admin-api/
* https://docs.konghq.com/gateway-oss/2.4.x/plugin-development/custom-entities/
