### ISSUE TITLE
Can you remove the sudo in the makefile ? 

### ISSUE THREAD

**Issue by ymolists** [Kong/docs.konghq.com#1179]
Maybe this is a left over. I cant see the rationale behind using the sudo in [here](https://github.com/Kong/docs.konghq.com/blob/master/Makefile#L5)

**Comment by hutchic** [comment]
because docker user is root after one runs `develop` the resulting `dist` and `node_modules` directory are both owned by root. We could remove `sudo` from the Makefile it just means folks would need to run `sudo make clean` which maybe that's fine (?)

**Comment by ymolists** [comment]
I would think a better fix would be to remove the root cause (ie not running as root) as well as removing the sudo.

**Comment by hutchic** [comment]
We'd welcome that PR
