### ISSUE TITLE
Update CORS plugin documentation with new Admin API notations

### ISSUE THREAD

**Issue by thibaultcha** [Kong/docs.konghq.com#1197]
See: https://docs.konghq.com/hub/kong-inc/cors/

### Summary

In Kong 1.0, the old comma-separated array notation (and JSON dot-notation) were removed (after being deprecated for several versions) in favor of better standards for both MIME types.

The new array notation is only documented in the Admin API reference, see [Add Route](https://docs.konghq.com/1.0.x/admin-api/#add-route), in the `hosts` or `paths` properties for example.

However, the CORS plugin still uses the comma notation, which will not pass schema validation and produce an error, preventing a user from adding a plugin by simply following our examples.

### Additional Details

- The comma notation is still valid for Kong < 1.0 and Kong EE. This revigorates the hot topic of versioning our plugins' documentation
- Ideally, a tab shows the same request with various snippets (i.e. with httpsnippet?) and Content-Type, since the dot notation is accepted for `form-encoded`, but not for `application/json` which must specify nested JSON Objects :warning: 
- :warning: Other plugins may also be susceptible to the same flaws and lagging behind
- We should also consider documenting the new notations under the Admin API's [Supported Content Types](https://docs.konghq.com/1.0.x/admin-api/#supported-content-types) section.

**Comment by falondarville** [comment]
This has been fixed.
