### ISSUE TITLE
Custom Nginx Template Wrong Documentation

### ISSUE THREAD

**Issue by flowdopip** [Kong/docs.konghq.com#1234]
https://docs.konghq.com/1.1.x/configuration/#custom-nginx-templates--embedding-kong

### Summary

The tree of nginx template are wrong, missing stream templates

Another this i expect is about configure the log_format, is not clear, i´ve take few hours to solve

SUMMARY_GOES_HERE

### Steps To Reproduce

1.https://docs.konghq.com/1.1.x/configuration/#custom-nginx-templates--embedding-kong

**Comment by falondarville** [comment]
We have added templates: 
* https://github.com/kong/kong/tree/master/kong/templates
* https://docs.konghq.com/gateway-oss/2.4.x/configuration/#custom-nginx-templates

Please feel free to re-open if you want to provide more info about `log_format`.
