### ISSUE TITLE
Funnel installation guides to Getting Started section for creating Super Admins

### ISSUE THREAD

**Issue by h3xar0n** [Kong/docs.konghq.com#1286]
- `docs.konghq.com` url(s):

### Summary

Currently, each Enterprise installation guide assumes a default configuration, e.g. with `enforce_rbac` off. As a result, there is no mention of setting `KONG_PASSWORD`, which is required at the time of migrations in order to create a Super Admin. The result is that users are starting Kong with RBAC on and without a Super Admin, which forces them to restart.

The solution is to either (1) direct users to Getting Started after they have installed, or (2) mention the caveat about Super Admins above the `migrations` steps in each Installation guide.

**Comment by Aswinpookkatt** [comment]
Issue still open?

**Comment by lena-larionova** [comment]
Issue resolved earlier this year, at some point. Installation guides now include instructions for setting `KONG_PASSWORD`.
