### ISSUE TITLE
Canary docs detailed info redirects to same page

### ISSUE THREAD

**Issue by Aswinpookkatt** [Kong/docs.konghq.com#1376]
### Summary

 In the Documentation of Canary plugin version .33x
link for detailed documentation for Enterprise canary release plugin redirects to same page.  
### Steps To Reproduce

1.goto the page https://docs.konghq.com/enterprise/latest/plugins/canary-release/
2.click on Detailed documentation for the Enterprise Canary Release Plugin.
This link redirects to same page.

**Comment by levfishbluefish** [comment]
Fixed in #1444
