### ISSUE TITLE
proxy-cache plugin documentation is out of sync

### ISSUE THREAD

**Issue by mesutcelik** [Kong/docs.konghq.com#1461]
Hi,

I see that there are differences between proxy-cache github readme and official documentation. Which one is the latest version?

https://github.com/Kong/kong-plugin-proxy-cache/blob/master/README.md
https://docs.konghq.com/hub/kong-inc/proxy-cache/

**Comment by levfishbluefish** [comment]
The README listed on the plugin's Github repository is the most up to date. We welcome PRs helping us keep our documentation site in sync with the plugins repositories.

**Comment by duncanleung** [comment]
I can take this issue to help update the docs on proxy-cache plugin.

**Comment by avats-dev** [comment]
Hi, @levfishbluefish I would like to work on this. Can you guide me how I can implement this?

**Comment by falondarville** [comment]
How to contribute to plug-in documentation: https://docs.konghq.com/contributing/plugin-docs/
