### ISSUE TITLE
Wrong ToC formatting on Request Transformer Advanced page

### ISSUE THREAD

**Issue by levfishbluefish** [Kong/docs.konghq.com#1508]
### Summary

see here: https://docs.konghq.com/hub/kong-inc/request-transformer-advanced/

the ToC (upper right) lists everything under a single header "Configuration", whereas from "parameters" on wards it should probably be on the top level again.

**Comment by agarwal-akash** [comment]
@h3xar0n 
I could not find where to edit the doc, tried searching [here](https://github.com/Kong/docs.konghq.com/tree/master/app/_hub/kong-inc/request-transformer-advanced). Could you guide me to the right place?

**Comment by lena-larionova** [comment]
Fixed in https://github.com/Kong/docs.konghq.com/pull/1841.
