### ISSUE TITLE
Broken Links on 0.36 Admin API page

### ISSUE THREAD

**Issue by levfishbluefish** [Kong/docs.konghq.com#1509]
- `docs.konghq.com` url(s): https://docs.konghq.com/enterprise/0.36-x/admin-api/rbac/examples/

### Summary

Since the navigation structure changed slightly, the URL paths are different.

The following links are broken:

- RBAC Overview 
- RBAC Admin API 
- Workspaces Examples Page
- Getting Started Guide 

Maintain the enterprise and version part of the path (`enterprise/{{page.kong_version}}/...`}, but fix the part with the file location.

The page must be free of 404s.

**Comment by nicohouillon** [comment]
submitted 2 PR 
(0.35) https://github.com/Kong/docs.konghq.com/pull/1556
(0.36) https://github.com/Kong/docs.konghq.com/pull/1557

**Comment by falondarville** [comment]
These fixes have been merged.
