### ISSUE TITLE
Update Enterprise Plugin links to point to Enterprise pages

### ISSUE THREAD

**Issue by levfishbluefish** [Kong/docs.konghq.com#1510]
Now that Core pages are copied into Enterprise 0.34-0.36, corresponding Plugin docs should direct to the Enterprise version of the page.

For example, in the Canary plugin, instead of a link for the Service object directing to the Kong 1.2.0 Admin API reference, it should direct to the Kong Enterprise 0.36 Admin API reference.

**Comment by X3NOSIZ** [comment]
@levfishbluefish can you assign me this issue?

**Comment by falondarville** [comment]
We're revisiting the strategy for Enterprise vs. OSS docs and plan to combine them in the future. Opting not to update, as we would have to do so again in the future when this strategic change happens.
