### ISSUE TITLE
stream_listen details missing on 0.36 Configuration page

### ISSUE THREAD

**Issue by h3xar0n** [Kong/docs.konghq.com#1527]
- `docs.konghq.com` url(s): https://docs.konghq.com/enterprise/0.36-x/property-reference/#stream_listen

### Summary

The property description for `steam_listen` is missing the following details from the conf file:

                        # which the stream mode should listen.
                         #
                         # This value accepts IPv4, IPv6, and hostnames.
                         # Some suffixes can be specified for each pair:
                         # - `proxy_protocol` will enable usage of the
                         #   PROXY protocol for a given address/port.
                         # - `transparent` will cause kong to listen to, and
                         #   respond from, any and all IP addresses and ports
                         #   you configure in iptables.

### Additional Details

Format correctly; tag @Kong/team-docs for review.

**Comment by agarwal-akash** [comment]
I would like to work on this!

**Comment by h3xar0n** [comment]
Thanks again, @agarwal-akash .
