### ISSUE TITLE
"Kong requires a running Cassandra cluster (3.x+) or PostgreSQL instance (9.6+) before it starts."

### ISSUE THREAD

**Issue by kikito** [Kong/docs.konghq.com#1536]
That phrase is visible in https://hub.docker.com/_/kong

It is no longer exact since 1.2.0 (Kong can run in db-less mode as well)

Originally reported in https://github.com/Kong/kong/issues/5074

**Comment by falondarville** [comment]
I have opened up DOCU-1565 to address this issue.
