### ISSUE TITLE
Better docs on headers appended by plugins

### ISSUE THREAD

**Issue by subnetmarco** [Kong/docs.konghq.com#163]
For example in "Rate Limiting" and "Response Rate Limiting", explain what headers are appended to the response and also what status codes it's being returned in case of an error.

Same applies for "IP Restriction" plugin, etc.

**Comment by p0pr0ck5** [comment]
Do we still need these? seems like every plugin has this now...

**Comment by coopr** [comment]
Still needed @subnetmarco ?
