### ISSUE TITLE
download kong studio page 404

### ISSUE THREAD

**Issue by kefatong** [Kong/docs.konghq.com#1845]
# download kong studio page 404

**Comment by lena-larionova** [comment]
@kefatong Please check that you're logged into Bintray before clicking those links, it will show a 404 if you aren't.

**Comment by mufasa71** [comment]
same here. getting 404 even when i am logged in

**Comment by lena-larionova** [comment]
@mufasa71 I just checked the links, they all seem to be working. Do you have access to the Kong repository on Bintray? Studio is an enterprise-only product, so you need to have Kong Enterprise and access to the Kong repo to download it. If you don't have access, that might also throw a 404.

**Comment by mufasa71** [comment]
@lena-larionova thanks for clarification, i did not read description, my bad.
