### ISSUE TITLE
broken sidebar link for "CA Certificate Object" in Kong Enterprise 1.5 Admin API reference

### ISSUE THREAD

**Issue by hishamhm** [Kong/docs.konghq.com#2030]
https://docs.konghq.com/enterprise/1.5.x/admin-api/

Click "CA Certificate Object" in the sidebar

**Comment by lena-larionova** [comment]
Thanks for catching it! Fixing in https://github.com/Kong/docs.konghq.com/pull/2031

**Comment by diefans** [comment]
The sidebar is broken for all entries except "Supported Content Types".

All anchors have a slash `/` appended and thus don't work.

**Comment by lena-larionova** [comment]
Fixed again; different issue this time: https://github.com/Kong/docs.konghq.com/pull/2127
