### ISSUE TITLE
Better OAuth 2.0 docs

### ISSUE THREAD

**Issue by subnetmarco** [Kong/docs.konghq.com#204]
Especially a better explanation of why `provision_key` is required and why it should be kept secret.

**Comment by viragumathe5** [comment]
Is this issue open to work

**Comment by levfishbluefish** [comment]
This particular case has been covered, but we are always open to improvements on our documentation

**Comment by falondarville** [comment]
The documentation has been improved: https://docs.konghq.com/hub/kong-inc/oauth2/
