### ISSUE TITLE
Conflicting timeout properties docs for Proxy Reference?

### ISSUE THREAD

**Issue by dlouzan** [Kong/docs.konghq.com#2120]
I'm confused by references to upstream timeout configuration between [Proxy Reference](https://docs.konghq.com/2.0.x/proxy/#3-proxying--upstream-timeouts) and [Admin API Service Object](https://docs.konghq.com/2.0.x/admin-api/#service-object). Are these two sets of configs applying to different configurations, or the same?

In https://docs.konghq.com/2.0.x/proxy/#3-proxying--upstream-timeouts:

```
upstream_connect_timeout: defines in milliseconds the timeout for establishing a connection to your upstream service. Defaults to 60000.
upstream_send_timeout: defines in milliseconds a timeout between two successive write operations for transmitting a request to your upstream service. Defaults to 60000.
upstream_read_timeout: defines in milliseconds a timeout between two successive read operations for receiving a request from your upstream service. Defaults to 60000.
```

In https://docs.konghq.com/2.0.x/admin-api/#service-object/:

```
connect_timeout optional The timeout in milliseconds for establishing a connection to the upstream server. Defaults to 60000.
write_timeout optional The timeout in milliseconds between two successive write operations for transmitting a request to the upstream server. Defaults to 60000.
read_timeout optional The timeout in milliseconds between two successive read operations for transmitting a request to the upstream server. Defaults to 60000.
```

Is it possible that the docs are just outdated? Googling I've found references for these `upstream_*` properties in pre-2.0 Kong versions.

**Comment by hishamhm** [comment]
@dlouzan You're correct, the docs are out of date!

The Admin API doc is correct and the Proxy Reference is wrong. The attributes are called `connect_timeout`, `write_timeout` and `read_timeout`.
