### ISSUE TITLE
Build failed when Develop Locally with Docker

### ISSUE THREAD

**Issue by kakascx** [Kong/docs.konghq.com#2498]
### Summary

 I wanna to contribute a new plugin to kong hub.I have finish the index.md.
But it built failed when develop locally with docker

### Steps To Reproduce

1. I have finish make install-prerequisites
2. when make develop, it built failed

### Additional Details

Here's the error log
```
docker-compose up
Creating docskonghqcom_jekyll_1 ... done
Attaching to docskonghqcom_jekyll_1
jekyll_1  | mkdir node_modules
jekyll_1  | chmod 777 node_modules
jekyll_1  | mkdir: can't create directory 'node_modules': Permission denied
jekyll_1  | make: [Makefile:6: install] Error 1 (ignored)
jekyll_1  | chmod: node_modules: No such file or directory
jekyll_1  | make: *** [Makefile:7: install] Error 1
docskonghqcom_jekyll_1 exited with code 2
```

**Comment by kakascx** [comment]
I reslove this problem by change the user to root in docker-compose.yml
```services:
  jekyll:
    build: .
    #user: ${JEKYLL_USER:-jekyll}
    user: root
    command: ${COMMAND:-make run}
    volumes:
      - .:/srv/jekyll
    ports:
      - 3000:3000
      - 3001:3001
    healthcheck:
      test: curl --fail -I localhost:3000
```

I can't make sure that it's my error operation before or a bug.
I executed the followings according to the readme.md[https://github.com/Kong/docs.konghq.com/blob/master/README.md](url)
```
make install-prerequisites
make develop
```

**Comment by kakascx** [comment]
It executed with following errors after solve the problem before
```
jekyll_1  | touch install
jekyll_1  | chmod -R 777 dist
jekyll_1  | chmod: dist: No such file or directory
jekyll_1  | make: [Makefile:15: run] Error 1 (ignored)
jekyll_1  | gulp
```

**Comment by falondarville** [comment]
This is a permissions issue. 

`sudo make install` creates directories at root level. Then, commands like `make develop` are executed at non-privileged user level and will fail.
