### ISSUE TITLE
Rate Limiting Plugin config.service_id not working

### ISSUE THREAD

**Issue by piyushpgupta** [Kong/docs.konghq.com#2546]
- `docs.konghq.com` url(s):

### Summary

 config.service_id field defined is not working .
Its unrecognised by the kong 

### Steps To Reproduce

1.Apply rate limiting plugin as below config  on global 
{
    "name":"rate-limiting",
    "config":{
        "second":5,
        "limit_by":"service",
        "service_id":"<>"
    },
    "service":{
        "id":"<>"
    }
}
2.Check the response
{
    "message": "schema violation (config.service_id: unknown field)",
    "name": "schema violation",
    "fields": {
        "config": {
            "service_id": "unknown field"
        }
    },
    "code": 2
}

### Additional Details

Kong version 2.3 and rate-limiting plugin version : latest

**Comment by lena-larionova** [comment]
When applying a plugin globally, you can't specify a service ID. You can set the plugin to "scoped" and apply the plugin to a service, or you can apply it globally and not attribute it to any specific element. If you need to do both, you'll need two different plugin configs.

See config examples here: https://docs.konghq.com/hub/kong-inc/rate-limiting/

Closing, as this is not a doc issue.
