### ISSUE TITLE
IngressClass definition is missing value for spec.controller

### ISSUE THREAD

**Issue by hanlaur** [Kong/docs.konghq.com#2585]
- `docs.konghq.com` url(s): https://docs.konghq.com/kubernetes-ingress-controller/1.1.x/concepts/ingress-versions/

### Summary

Creating IngressClass using documentation instructions fails due to missing `spec.controller` field. I searched a bit, but I could not yet find the intended value for this parameter. Documentation fix would be good for this.

(The helm chart did not seem to create this object automatically)

### Steps To Reproduce

1. Create IngressClass YAML per documentation
```
$ cat ingressclass.yaml 
---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: kong
spec:
```
2. Applying the YAML fails
```
$ kubectl apply -f ingressclass.yaml
The IngressClass "kong" is invalid: spec.controller: Required value
```

### Additional Details

Kubernetes server & client version: 1.20.2

**Comment by lena-larionova** [comment]
@rainest Can you take a look at this issue? I can't find anything on the `spec.controller` parameter either.

**Comment by rainest** [comment]
We don't currently make use of the IngressClass controller field for any filtering in our code, and don't actually require any value for it.

I recommend using `konghq.com/ingress-controller` for now to follow the convention.
