### ISSUE TITLE
Duplicate entries in the PDK navigation column

### ISSUE THREAD

**Issue by dndx** [Kong/docs.konghq.com#2679]
https://docs.konghq.com/gateway-oss/2.3.x/pdk/kong.node/

Note that `kong.node` appeared twice.

![image](https://user-images.githubusercontent.com/1131072/110679671-af7a9280-8212-11eb-9c64-72ed9274bc1f.png)

**Comment by lena-larionova** [comment]
@kikito this is one of the autodoc-created nav pieces - do you know if something changed recently?

**Comment by lena-larionova** [comment]
Fixed in #2753.
