### ISSUE TITLE
Konnect helm docs

### ISSUE THREAD

**Issue by jackkav** [Kong/docs.konghq.com#2728]
- `https://docs.konghq.com/konnect/runtime-manager/kong-gateway-runtime/`

### Summary

- Docs should specify helm 3 is a requirement and install command should include `--set ingressController.installCRDs=false` flag
- it should be clearer that the create secrets are expecting the reader to have stored the certs in /tmp/
- create secrets should include namespace flag `-n kong`
- yml + yaml inconsisency

**Comment by jackkav** [comment]
In order for reporting to work an additional line must be included in the env section of values.yaml in the docs 
`vitals_ttl_days=732`
![image](https://user-images.githubusercontent.com/3679927/113390025-46111e00-9391-11eb-9cc1-f96e057ce00b.png)

**Comment by lena-larionova** [comment]
@jackkav Is `KONG_VITALS_TTL_DAYS` a new parameter? I don't see it in kong.conf: https://github.com/Kong/kong-ee/blob/next/2.3.x.x/kong.conf.default

**Comment by lena-larionova** [comment]
> --set ingressController.installCRDs=false 

Included this directly in the values.yaml instead, to simplify.

**Comment by lena-larionova** [comment]
Fixed in https://github.com/Kong/docs.konghq.com/pull/2750.
