### ISSUE TITLE
KongClusterPlugin section should describe how to configure global plugin

### ISSUE THREAD

**Issue by fffonion** [Kong/docs.konghq.com#2748]
Currently, "Configure a global plugin" lives under "Using KongPlugin resource" section(https://docs.konghq.com/kubernetes-ingress-controller/1.2.x/guides/using-kongplugin-resource/#configure-a-global-plugin), but it's actually telling
about usage about `KongClusterPlugin` resource.
It can be moved to and "Using KongClusterPlugin resource" section,
and a link to the new place will appear in the old section.

From https://github.com/Kong/kong/issues/6984

**Comment by lena-larionova** [comment]
Looks like the "Using KongPlugin resource" section in https://docs.konghq.com/kubernetes-ingress-controller/1.2.x/guides/using-kongplugin-resource/#configure-a-global-plugin doesn't actually add any info that the specific `KongClusterPlugin` topic doesn't have. It does have better lead-in and descriptive text, so we can make use of that, but you're right - this doesn't belong here and is mostly confusing.
