### ISSUE TITLE
Docker Pull kong-enterprise-edition forbidden

### ISSUE THREAD

**Issue by raphaelcb** [Kong/docs.konghq.com#2813]
- `docs.konghq.com` url(s): https://docs.konghq.com/enterprise/2.3.x/deployment/installation/docker/

### Summary
When executed the step 1 - pull the Kong Gateway Docker image is happening error 403 - Forbidden

### Steps To Reproduce

1. Open Ubuntu terminal
2. docker pull kong-docker-kong-gateway-docker.bintray.io/kong-enterprise-edition:2.3.3.0-alpine
3. The output console:
2.3.3.0-alpine: Pulling from kong-enterprise-edition
e95f33c60a64: Pulling fs layer 
4019b401b901: Pulling fs layer 
8bd0409da4b5: Pulling fs layer 
613348f346f2: Waiting 
error pulling image configuration: error parsing HTTP 403 response body: invalid character 'F' looking for beginning of value: "Forbidden!"

**Comment by lena-larionova** [comment]
Looks like there's a Bintray brownout going on right now: https://status.bintray.com/

We are migrating these images from Bintray currently as well, and will have a stable site for the packages in the near future. Thanks for your patience!

**Comment by lena-larionova** [comment]
@raphaelcb we're updating this in the docs, but you can pull the latest docker image from Docker Hub now:
```
docker pull kong/kong-gateway:2.3.3.2-alpine
```

For all the versions and distributions, see: https://hub.docker.com/r/kong/kong-gateway/tags?page=1&ordering=last_updated&name=alpine

**Comment by raphaelcb** [comment]
> ```
> docker pull kong/kong-gateway:2.3.3.2-alpine
> ```

Thanks @lena-larionova .... I got it through command above.
