### ISSUE TITLE
Cannot remove the json property in the body response using kong response-transformation plugin?

### ISSUE THREAD

**Issue by mervekocagoz** [Kong/docs.konghq.com#2851]
### Summary

I cannot remove the JSON property in the body response using the kong response-transformation plugin? 

Example of a response body:
[
{
"id": 1,
"name": "Leanne Graham",
"username": "Bret",
"email": "Sincere@april.biz",
"address": {
"street": "Kulas Light",
"suite": "Apt. 556",
"city": "Gwenborough",
"Message": "92998-3874",
"InnerItems": {
"lat": "-37.3159",
"lng": "81.1496"
}
]

### Steps To Reproduce

1. I'am trying this command
curl -X POST http://localhost:8001/routes/Route-For-Product-DepartmentList/plugins --data "name=response-transformer" --data "config.remove.json=InnerItems" --data "config.remove.json= Message"

2. I saw on konga that plugging is added.
image-1
![image](https://user-images.githubusercontent.com/78708887/118381389-1e99ac00-b5f3-11eb-8f69-edf2ea10b6e0.png)

image-2
https://user-images.githubusercontent.com/78708887/118380546-48e76b80-b5eb-11eb-8f1d-615f9afbb8eb.png

3. But i still see the Message and InnerItems on JSON

**Comment by falondarville** [comment]
`config.remove.json` is only available with the advanced plugin: https://docs.konghq.com/hub/kong-inc/response-transformer-advanced/
