### ISSUE TITLE
missing name for openid-connect plugin

### ISSUE THREAD

**Issue by dimitropoulos** [Kong/docs.konghq.com#2887]
- `docs.konghq.com` url(s): https://docs.konghq.com/hub/kong-inc/openid-connect/#parameters

### Summary

The name needed for the openid-connect plugin is missing.  I tried to see where this was set to submit a quick PR but I was unable to locate where this needs to be set.

see after "in this case":

![Screenshot_20210526_145650](https://user-images.githubusercontent.com/15232461/119715974-9c02bf00-be32-11eb-892d-03340e889eff.png)

**Comment by tlblessing** [comment]
Thanks for noticing this issue @dimitropoulos. @bungle is currently refactoring OIDC docs in this PR https://github.com/Kong/docs.konghq.com/pull/2861

**Comment by HCloward** [comment]
> Thanks for noticing this issue @dimitropoulos. @bungle is currently refactoring OIDC docs in this PR #2861

This issue is definitely addressed in @bungle 's PR
