### ISSUE TITLE
Add "Disallow" statements to robots.txt to get old versions out of search results

### ISSUE THREAD

**Issue by hhoover** [Kong/docs.konghq.com#2890]
- `docs.konghq.com` url(s):
All old versions:
enterprise/[0.31-x-2.3.x]
mesh/1.0.x
mesh/1.1.x
gateway-oss/[0.2.x-2.3.x]
kubernetes-ingress-controller/[1.0.x-1.1.x]

### Summary

Add `Disallow: /X` statements to `app/robots.txt` for any old versions. This will keep these pages out of Google search results.

Example:

```
---
layout: null
---
User-agent: *
Disallow: /enterprise/0.31-x/*
Disallow: /enterprise/2.3.x/*
...etc...
Sitemap: {{site.links.web}}/sitemap.xml
```

### Steps To Reproduce

Current "from Google" user flow:
1. Search for kong documentation
2. find old version page in top results
3. click through old page, get told you are on an old version, click new docs link.

**Comment by lena-larionova** [comment]
That's frustrating. We've attempted various solutions to keep the old versions out of search results that are less extreme, but looks like it hasn't been enough. Will give this a try and see if it helps, thanks!
