### ISSUE TITLE
KIC 2.0: UDPIngress End-User Docs (docs.konghq.com)

### ISSUE THREAD

**Issue by mflendrich** [Kong/docs.konghq.com#2903]
UDPIngress support will come in KIC 2.0.

The scope of this issue is to document UDPIngress under the 2.0 version on docs.konghq.com.

**Comment by shaneutt** [comment]
This is resolved in that the documentation is written, but there is a follow up for the final merge to `main`: https://github.com/Kong/kubernetes-ingress-controller/issues/1719

**Comment by mflendrich** [comment]
Additional acceptance criteria for closure of this item:
- [ ] a guide for UDP Ingress is present in the docs.konghq.com 2.0 beta branch
- [ ] a list of documentation bits on UDP Ingress is present in a comment of this issue.
