### ISSUE TITLE
KIC 2.0: Document new flags

### ISSUE THREAD

**Issue by mflendrich** [Kong/docs.konghq.com#2904]
KIC 2.0 adds new flags.

Acceptance criteria:
- [x] new flags documented
- [x] flag descriptions on docs.konghq.com match the flag set exposed by KIC 2.0

**Comment by Bradamant3** [comment]
@mflendrich Do we have a way to generate flag values and descriptions from the code?

**Comment by mflendrich** [comment]
> @mflendrich Do we have a way to generate flag values and descriptions from the code?

Yes. Running the application with `--help` should do it.

**Comment by shaneutt** [comment]
This is resolved in that the documentation is written, but there is a follow up for the final merge to `main`: https://github.com/Kong/kubernetes-ingress-controller/issues/1719

**Comment by mflendrich** [comment]
The controller enablement flags are not accurately documented now - the docs site refers to the `EnablementStatus` type which is no longer the case (the flags are now `bool`s).

**Comment by shaneutt** [comment]
https://github.com/Kong/docs.konghq.com/pull/3120 makes a PR to the open PR to change the recently updates flags.
