### ISSUE TITLE
Update integration documentation for using kong with knative 

### ISSUE THREAD

**Issue by ccfishk** [Kong/docs.konghq.com#2939]
- `docs.konghq.com` url(s):

### Summary

Provide step by step guidance for configuring kong with knative. 

Also, correct some details within 1.3.x documentation
https://docs.konghq.com/kubernetes-ingress-controller/1.3.x/guides/using-kong-with-knative/#documentation

**Comment by lena-larionova** [comment]
Hi @ccfishk ! Thanks for your submission, but we need more information to go on. 

> Also, correct some details within 1.3.x documentation
https://docs.konghq.com/kubernetes-ingress-controller/1.3.x/guides/using-kong-with-knative/#documentation

Can you please point out what is incorrect in the document that you linked?

Re:
>  Provide step by step guidance for configuring kong with knative.

What exactly are you asking for here? If you looking for instructions from the knative side, we generally don't document external products/software. Can you please specify what you think is missing?

**Comment by ccfishk** [comment]
> https://docs.konghq.com/kubernetes-ingress-controller/1.3.x/guides/using-kong-with-knative/#documentation
Incorrect Part:

kubectl patch configmap/config-network \
  --namespace knative-serving \
    --type merge \
      --patch '{"data":{"ingress.class":"kong"}}'
"kong" is a default ingress.class name, and the value is configurable.

echo '
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-domain
  namespace: knative-serving
  labels:
    serving.knative.dev/release: v0.13.0
data:
  35.247.39.83.xip.io: "" <<<<<---- dont need the subdomain, LB external cluster ip/hostname would be good satisfy the configuration.
' | kubectl apply -f -
configmap/config-domain configured

For convenience, user is able to access the service using following format
curl --header "Host: http://svc-name.namespace.proxy-hostname" http://proxy-hostname-ip

**Comment by d19dotca** [comment]
FYI - [This Docs page](https://docs.konghq.com/kubernetes-ingress-controller/latest/guides/overview/#main) currently links to [this doc page](https://docs.konghq.com/kubernetes-ingress-controller/2.5.x/guides/using-kong-with-knative) for using Kong with knative and is unfortunately responding with a 404. We have customers asking if this is still supported as a result of it being inaccessible in the documentation.

**Comment by lena-larionova** [comment]
This issue was fixed in the older version.

In the latest versions of KIC, [Knative is no longer supported](https://github.com/Kong/kubernetes-ingress-controller/issues/2813), (see the [notice in the docs as well](https://docs.konghq.com/kubernetes-ingress-controller/3.3.x/upgrade/kic/#upgrade-30:~:text=Remove%20the%20Knative,you%20use%20them.)) so this doc no longer exists.
