### ISSUE TITLE
Kong Developer Portal Networking ToC broken/out of date

### ISSUE THREAD

**Issue by tjrivera** [Kong/docs.konghq.com#3068]
### What part of the site needs attention?

https://github.com/Kong/docs.konghq.com/blob/main/app/enterprise/2.3.x/developer-portal/networking.md

### Summary

This page redirects to dev portal property references on the 1.5.x version of Kong

### Steps To Reproduce

https://docs.konghq.com/enterprise/2.3.x/developer-portal/using-the-editor/

<img width="1509" alt="Screen Shot 2021-07-29 at 1 53 30 PM" src="https://user-images.githubusercontent.com/4405800/127541358-334b2a99-8071-4bc9-aa09-d0579f96812d.png">

**Comment by falondarville** [comment]
Thank you so much, @tjrivera. This has been resolved.
