### ISSUE TITLE
Still-supported license loading methods no longer documented

### ISSUE THREAD

**Issue by rainest** [Kong/docs.konghq.com#3069]
### What part of the site needs attention?
https://docs.konghq.com/enterprise/2.4.x/deployment/licenses/deploy-license/

### Summary
Loading licenses via the `KONG_LICENSE_DATA` environment variable is still supported in 2.4, but has been removed from documentation. We still recommend this method for Kubernetes deployments because they typically use environment variables whenever possible, and cannot easily add licenses to the filesystem.

The omission has caused some confusion, since it suggests this method is no longer available: https://github.com/Kong/charts/issues/412

Requesting we restore the tab at https://github.com/Kong/docs.konghq.com/blame/ff4cd66e2f50e9acf9789cf7f4f8fbe0c94e8ca3/app/enterprise/2.3.x/deployment/licenses/deploy-license.md#L84-L109 to the 2.4 docs and keep it in place going forward.

**Comment by falondarville** [comment]
Thank you, @rainest ! We have added this tab back in.
