### ISSUE TITLE
Example Requests for Event Hook Operations

### ISSUE THREAD

**Issue by avles** [Kong/docs.konghq.com#3092]
### What part of the site needs attention?

https://docs.konghq.com/enterprise/2.5.x/admin-api/event-hooks/reference/

### Summary

Documentation related to POST operations can be enhanced with example "requests".  Currently, it shows example of just responses.
  
https://docs.konghq.com/enterprise/2.5.x/admin-api/event-hooks/reference/#add-a-lambda-event-hook

**Comment by lena-larionova** [comment]
Please see https://docs.konghq.com/enterprise/2.5.x/admin-api/event-hooks/examples/ for the example requests you're looking for. 

Adding request examples to the reference page is a good idea, but would have to be part of a larger project to improve the API doc as a whole. We'll take it into consideration for our next round of doc improvements.

Closing this issue as the requested doc already exists.
