### ISSUE TITLE
Missing Steps for GKE - “If you wish to use a static IP for Kong, you have to reserve a static IP address”

### ISSUE THREAD

**Issue by eddadjei** [Kong/docs.konghq.com#3093]
### What part of the site needs attention?
totally ignored what needs to be done in pass a static IP to GKE => “If you wish to use a static IP for Kong, you have to reserve a static IP address”

**Comment by falondarville** [comment]
Hi @eddadjei - we don't have enough information to make this actionable. If you'd like to contribute to improvements of our docs, please submit a PR with the changes you're expecting!
