### ISSUE TITLE
Illegal values.yaml in Kong Konnect guide

### ISSUE THREAD

**Issue by rahulrai-in** [Kong/docs.konghq.com#3138]
The `values.yaml` file specified in the Kong Konnect dashboard has illegal values for the repository and tag parameters as follows.

![image](https://user-images.githubusercontent.com/11886524/130790639-c4bdd497-5831-4866-b84e-eee9aef76d80.png)

The correct values should be:

  repository: kong/kong-gateway
  tag: 2.4.1.1-alpine

**Comment by lena-larionova** [comment]
Hi @rahulrai-in , thanks for bringing this to our attention! I've filed a ticket with the Konnect team to address this issue. In the meantime, you can follow the documentation, which has the correct values: https://docs.konghq.com/konnect/runtime-manager/gateway-runtime-kubernetes/

**Comment by lena-larionova** [comment]
This is now fixed in the Konnect UI.
