### ISSUE TITLE
Make the docs left sidebar menu tab-friendly

### ISSUE THREAD

**Issue by falondarville** [Kong/docs.konghq.com#3151]
### Where is the problem?

Our left sidebar menu is not [WCAG 2.1 accessible](https://www.w3.org/TR/UNDERSTANDING-WCAG20/keyboard-operation-keyboard-operable.html). The current docs sidebar on docs detail pages are difficult to tab through. When I land on a topic and ENTER on my keyboard, I go to the page and doesn't open the submenu. Also, when I tab through, I lose FOCUS and don't know what I'm tabbed over. 

The left-side sidebar appears on multiple pages, including: 
https://docs.konghq.com/konnect/

The code lives here: 
https://github.com/Kong/docs.konghq.com/blob/main/app/_includes/docs-sidebar.html

### What is your suggestion?

Make the left sidebar menu:
* Clearly tabbable through all elements
* I don't lose focus as I tab through 
* I can easily get to any page from the left sidebar using my keyboard only

Try this out yourself by going to https://docs.konghq.com/konnect/ and tabbing through the left sidebar menu. 

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by Kamlesh72** [comment]
can we discuss this further more?

**Comment by Kamlesh72** [comment]
@lena-larionova can you help me with this?

**Comment by lena-larionova** [comment]
@Kamlesh72 sure - can you please specify what help you need?

**Comment by Techie-Manju** [comment]
@lena-larionova @falondarville I understood the ticket somewhat and will try to draft a PR on this. You can get me this ticket and Kamlesh72 can follow up with me to complete this one.

**Comment by fabianrbz** [comment]
Fixed by https://github.com/Kong/docs.konghq.com/pull/6657
