### ISSUE TITLE
Fix Docker local setup for docs site local development

### ISSUE THREAD

**Issue by falondarville** [Kong/docs.konghq.com#3152]
### Where is the problem?

Our current Docker local setup does not work. Our GitHub workflow that uses the Docker container works, but we cannot develop locally using Docker. 

**This works in GitHub Actions for link checking**: https://github.com/Kong/docs.konghq.com/blob/main/.github/workflows/build-test.yml

**Dockerfile**: https://github.com/Kong/docs.konghq.com/blob/main/Dockerfile

**docker-compose file**: https://github.com/Kong/docs.konghq.com/blob/main/docker-compose.yml

### What is your suggestion?

Get our Docker local setup working so we can develop within a Docker container. 

Also, write up some simple instructions on using Docker locally that we can add to our README. 

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by SSwayam99** [comment]
I can try to solve this issue.
/assign

**Comment by falondarville** [comment]
@SSwayam99 done!
