### ISSUE TITLE
Improve pop-out mobile left sidebar menu 

### ISSUE THREAD

**Issue by falondarville** [Kong/docs.konghq.com#3153]
### Where is the problem?

On screen width 800px and under:

* On **Overview** pages, the left sidebar menu cannot be opened
* On **non-Overview** pages, the left sidebar menu can be opened but the icon is difficult to spot and not intuitive. 

![Screen Shot 2021-08-27 at 2 52 35 PM](https://user-images.githubusercontent.com/22301405/131192560-0dd8e09f-105a-4546-b3a9-ab4a69eb9735.png)

Overview page example where I cannot open the left sidebar menu on screen width 800px and under: https://docs.konghq.com/enterprise/

Non-Overview page where the icon is difficult to find: https://docs.konghq.com/enterprise/2.5.x/support-policy/

### What is your suggestion?

1. On Overview pages, enable the user to open the left sidebar menu
2. On non-Overview pages, create a more clear way for users to open the left sidebar menu - make it stand out more

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by Rutam21** [comment]
@falondarville I was trying to replicate the issue you pointed out. But the side navbar seems to be working fine and the placement of the icon on non-overview pages is also visible and not sticking to edges or something. Please find the screenshots below. Maybe you can look into these and confirm if you are still facing this issue or the pages are different that have this issue.

## Overview Page (Width- 500px)

![image](https://user-images.githubusercontent.com/47860497/134822066-1665a652-e4dc-480c-bf08-578590a3572c.png)

## Non-Overview Page (Width- 500px)

> Note: Proper margins are maintained and the icon is clearly visible.

![image](https://user-images.githubusercontent.com/47860497/134822149-582212f1-bf29-4d0f-984b-97a79bfd4b3e.png)

> Note: Clicking on it opens the navbar perfectly.

![image](https://user-images.githubusercontent.com/47860497/134822191-61010b08-cb23-4ddb-a6b0-d5634339010b.png)

**Comment by lena-larionova** [comment]
Hi @Rutam21 see some of the unversioned doc overview pages, such as https://docs.konghq.com/konnect/.

Notice that the icon is missing:
![Screen Shot 2021-09-27 at 3 19 27 PM](https://user-images.githubusercontent.com/54370747/134993056-d6071f84-04a9-4cd1-964b-4f688fa341b8.png)

**Comment by Rutam21** [comment]
@lena-larionova Thanks for the update. I will try to dig a bit up and see how this can be fixed. Which ones would fall under this unversioned Doc type other than this page?

**Comment by falondarville** [comment]
Unversioned doc pages (overview pages):

- https://docs.konghq.com/konnect-platform/
- https://docs.konghq.com/konnect/

Looking at the initial issue again, that screenshot is a versioned example to show how difficult and non-intuitive the icon is.
