### ISSUE TITLE
Improve 404 page

### ISSUE THREAD

**Issue by falondarville** [Kong/docs.konghq.com#3154]
### Where is the problem?

The 404 page needs some sprucing up. 

Example 404 page: https://docs.konghq.com/404

### What is your suggestion?

* remove the left sidebar menu
* surprise us! Use your creativity to come up with a fun 404 page that represents Kong!

Note that you should leave the OPEN SOURCE breadcrumb. 

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by Rutam21** [comment]
@lena-larionova I would love to use some creativity and bring the Kong mascot in there that would be fun for the users.

**Comment by lena-larionova** [comment]
Thanks for the interest on this issue, we'd appreciate the effort! 🦍

**Comment by falondarville** [comment]
Closing as this PR has been merged. Thank you again, @Rutam21!
