### ISSUE TITLE
decK CLI docs: Improve the Go → Markdown doc generation

### ISSUE THREAD

**Issue by lena-larionova** [Kong/docs.konghq.com#3155]
### Where is the problem?

Our [decK CLI documentation](https://docs.konghq.com/deck/1.7.x/reference/deck/) is currently generated directly out of the Go code for decK. The output in the docs is the default markdown generated from a cobra command.

The default output for flags gets generated into one giant codeblock, which doesn't look great and is hard to read:

![Screen Shot 2021-08-27 at 2 59 47 PM](https://user-images.githubusercontent.com/54370747/131193284-cc899ead-10d7-4f03-b797-7dc6697624ee.png)

### Ideal format

We'd like the generated documentation to look like this: 

* Convert the command name into `title` metadata instead of a heading
* Don't print the short description, only print the long description

```
 ---
 title: deck validate
 ---
    
The validate command reads the state file and ensures validity.
It reads all the specified state files and reports YAML/JSON
parsing issues. It also checks for foreign relationships
and alerts if there are broken relationships, or missing links present.
No communication takes places between decK and Kong during the execution of
this command.
```

* Split out flags into definition list entries and their descriptions. For example, the options section for `deck validate` would look like this:

```
### Options

`-h`, `--help`
: Help for validate.

`--rbac-resources-only`
: Indicate that the state file(s) contain RBAC resources only (Kong Enterprise only)

`-s`, `--state <strings>`
: File(s) containing Kong's configuration. This flag can be specified multiple times for multiple files. Use '-' to read from stdin. (default [kong.yaml])
```

* `### SEE ALSO` header should be `### See also`

### Files and references
* [decK repository](https://github.com/Kong/deck)
  * [File that generates the docs](https://github.com/Kong/deck/blob/main/docs/generate-docs.go)
  * [`cmd` files](https://github.com/Kong/deck/tree/main/cmd) that the generator uses to generate the output
* Cobra custom modules that we can use to customize the output: `GenMarkdownCustom`/`GenMarkdownTreeCustom` https://github.com/spf13/cobra/blob/master/doc/md_docs.go#L53
* Output gets copied over into [these files](https://github.com/Kong/docs.konghq.com/tree/main/app/deck/1.7.x/reference) in the docs.konghq.com repository

### Testing your changes
You can test any changes you make locally. Make sure you have set up the docs.konghq.com [local dev environment](https://github.com/Kong/docs.konghq.com#run-locally-with-gulp), then go through the following steps:

1. Generate decK CLI doc:
   1. Install Go (at least v1.16) on the machine where you want to generate the docs.
   2. `git clone Kong/deck`, then navigate to this repo through your terminal.
   3.  Run `make generate-cli-docs` . This will generate docs into the `docs/cli-docs` directory in the repo.

Copy the generated files from the decK repo docs/cli-docs directory (except for `deck_completion.go`) into the docs.konghq.com repo, `app/deck/1.7.x/reference` directory.

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by cool-coder-here** [comment]
I am somewhat familiar with the decK CLI and will try to solve this problem. Starting to work on this.
