### ISSUE TITLE
Copyedit the Proxy Reference page

### ISSUE THREAD

**Issue by falondarville** [Kong/docs.konghq.com#3156]
### Where is the problem?

https://docs.konghq.com/enterprise/2.5.x/proxy/

### What happened?

The Proxy Reference page could use a good copyedit! 

### What did you expect to happen?

* clean up the content
* remove "Back to Top" links

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by Sayanta66** [comment]
@falondarville I want to take this issue. Please assign this to me.

**Comment by falondarville** [comment]
> @falondarville I want to take this issue. Please assign this to me.

Great @Sayanta66!! Thanks so much, I've assigned this Issue to you! Please note that this is part of the Summit Hackathon 2021 (Sept 21-28) and there's more info here: https://github.com/Kong/docs.konghq.com/issues/3189.

**Comment by Sayanta66** [comment]
Thanks a lot @falondarville

**Comment by falondarville** [comment]
Closing this out as it's been resolved. Thank you, @Sayanta66!
