### ISSUE TITLE
Enable key auth plugin output is very odd

### ISSUE THREAD

**Issue by AshisRanjanDey** [Kong/docs.konghq.com#3181]
curl -X POST http://<admin-hostname>:8001/routes/mock/plugins \
  --data name=key-auth

this command gives output:
{"message":"Not found"} 
but works

**Comment by Bradamant3** [comment]
Hi @AshishThakur -- with apologies if this feels like giving you the runaround, but this isn't an issue we can address in the docs; it's part of the code so if you'd like to see it addressed please file in the Kong/kong repository. Thanks!
