### ISSUE TITLE
Kong 2.1.2 routes are redirecting when use regex

### ISSUE THREAD

**Issue by khotaditya** [Kong/docs.konghq.com#3190]
Hello,

I have 3 routes configured in a service using regular expression
route A: `/v3/catalog/(?<country_code>.+)/brands/(?<brand>.+)`
route B: `/v3/catalog/(?<country_code>.+)/brands/(?<brand>.+)/models`
route C: `/v3/catalog/(?<country_code>.+)/models/(?<model>.+)`

All routes having same host with following config:
"strip_path": false,
"preserve_host": false,
"regex_priority": 0,
"methods": [
    "GET"
  ],
"protocols": [
    "http",
    "https"
  ],

When I request to route A (/v3/catalog/**_DE_**/brands/**_SK_**), kong redirects to /v3/catalog/DE/brands/SK/api/v3/catalog/DE/brands/SK and gives Status 404.

When I request to route B (/v3/catalog/**_DE_**/brands/**_SK_**/models), it gives Status 200.

When I request to route C (/v3/catalog/**_DE_**/models/**_model:001_**), kong redirects to /v3/catalog/DE/models/model:001/api/v3/catalog/DE/models/model1 and gives Status 404.

The upstream server gives 200 to all routes.

The interesting thing is if I add "/" at the end of URI param then I get Status 200.
For example:
https://{{api_endpoint}}/v3/catalog/**_DE_**/brands/**_SK_**/  ====>  Status 200
https://{{api_endpoint}}/v3/catalog/**_DE_**/brands/**_SK_**/models  ====> Status 200
https://{{api_endpoint}}/v3/catalog/**_DE_**/models/**_model:001_**/  ====> Status 200

So the question is, why kong behaving this when we put regex at the end of the URI without "/".

Please help me if I'm doing something wrong.

**Comment by lena-larionova** [comment]
Hi @khotaditya ! This repository is for Kong documentation, and the docs team is unable to help with technical questions. 

Please ask this question in the Kong code repository: https://github.com/Kong/kong/discussions, or file an issue there: https://github.com/Kong/kong/issues.
