### ISSUE TITLE
OpenID Connect Plugin documentation incorrect regarding config.auth_method userinfo support

### ISSUE THREAD

**Issue by jgtr-coats** [Kong/docs.konghq.com#3201]
### Where is the problem?

https://docs.konghq.com/hub/kong-inc/openid-connect/#user-info-authentication

### What is your suggestion?

The Open ID Connect Plugin documentation for 2.0.0+ states that **userinfo** is a valid option for **config.auth_method**, however having tried this in Kong 2.3 which we are currently using and the latest version 2.5 both return this as being invalid.

I also can't see anything in the enterprise changelog about this authentication method being added/removed so can this be removed or at least flagged as a future feature that isn't currently available.

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by mheap** [comment]
It looks as though the field is named `config.auth_methods`. Does this work for you?

**Comment by lena-larionova** [comment]
We have reworked the plugin docs some time back, and the `userinfo` auth method was added in 2.6: https://docs.konghq.com/hub/kong-inc/openid-connect/changelog/#kong-gateway-26x
