### ISSUE TITLE
Copyedit Correlation ID plugin documentation

### ISSUE THREAD

**Issue by falondarville** [Kong/docs.konghq.com#3202]
### Where is the problem?

https://docs.konghq.com/hub/kong-inc/correlation-id/#how-it-works

### What happened?

Some current language is not in alignment with our style guide and contains needless complexity. Additionally, there are some grammatical errors. 

**Note**: Only edit content starting at the [**How it Works**](https://docs.konghq.com/hub/kong-inc/correlation-id/#how-it-works) section, as the content above is generated. 

This is the file to edit: https://github.com/Kong/docs.konghq.com/blob/c47c8e0dc1f45c3fc37b60a2e41bd859b1712c5f/app/_hub/kong-inc/correlation-id/index.md

### What did you expect to happen?

Clear, simple language in accordance with our [style guide](https://docs.konghq.com/contributing/style-guide/). 

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by Sayanta66** [comment]
Can you assign this to me? @falondarville

**Comment by falondarville** [comment]
Hi @Sayanta66, yes. I'm going to hold off on assigning the other Issues all to you right now as others may want to contribute! But I can assign them one at a time as you get through them! Thanks so much for your contributions. 🎉

**Comment by Rutam21** [comment]
@lena-larionova @falondarville I am done with my previous tickets. I would love to work on this now.

**Comment by falondarville** [comment]
Closing as the PR has been merged. 🚀
