### ISSUE TITLE
Test and edit Kong Gateway (OSS) Quickstart guide

### ISSUE THREAD

**Issue by HCloward** [Kong/docs.konghq.com#3205]
### Where is the problem?

https://docs.konghq.com/gateway-oss/2.5.x/getting-started/quickstart/

### What happened?

The Kong Gateway (OSS) Quickstart guide has not been tested or edited for a while and it could use some attention. It would be really helpful if someone were to test the steps to be sure they work as expected and look for any wording or grammar issues that might also need addressing.

### What did you expect to happen?

Accurate steps for completing the following quickstart procedures:

* [Start Kong Gateway](https://docs.konghq.com/gateway-oss/2.5.x/getting-started/quickstart)
* [Configure a Service](https://docs.konghq.com/gateway-oss/2.5.x/getting-started/configuring-a-service)
* [Configure a gRPC Service](https://docs.konghq.com/gateway-oss/2.5.x/getting-started/configuring-a-grpc-service)
* [Enable plugins](https://docs.konghq.com/gateway-oss/2.5.x/getting-started/enabling-plugins)
* [Add Consumers](https://docs.konghq.com/gateway-oss/2.5.x/getting-started/adding-consumers)

Clear, simple language in accordance with our style guide.

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by Rutam21** [comment]
@HCloward @falondarville I would love to work on this. Please assign this to me.

**Comment by Sayanta66** [comment]
@HCloward I already completed my previous tasks...can I take this issue next?

**Comment by Rutam21** [comment]
I am currently working on this issue. Would make sure the pages are in sync with the style guide. Any contributor who wants to test the steps and update any if required can work with me as I am having configuration issues on my Win11 machine.

**Comment by falondarville** [comment]
Closing because the PR has been merged.
