### ISSUE TITLE
Copyedit Rate Limiting plugin documentation

### ISSUE THREAD

**Issue by lena-larionova** [Kong/docs.konghq.com#3206]
### Where is the problem?

https://docs.konghq.com/hub/kong-inc/rate-limiting

### What happened?

The current language is not in alignment with our style guide and contains needless complexity. Additionally, there are some grammatical and formatting errors.

File to edit: https://github.com/Kong/docs.konghq.com/blob/main/app/_hub/kong-inc/rate-limiting/index.md

**Note:** Only edit content starting at the [**Headers sent to the client**](https://docs.konghq.com/hub/kong-inc/rate-limiting/#headers-sent-to-the-client) section (line 185 onward), as the content above it is generated.

#### Examples of problems
* "The plugin supports three policies, which each have their specific pros and cons." - Awkward phrasing
* The table and explanatory text in **Implementation considerations** have many sentences that start with lowercase
* The **Note** elements are formatted with HTML where they should be in markdown (see Kong docs guidelines for adding admonitions for the markdown formatting).

### What did you expect to happen?

Clear, simple language in accordance with our style guide.

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by Sayanta66** [comment]
Can I take this issue @lena-larionova ?

**Comment by Sayanta66** [comment]
Please assign this issue to me

**Comment by AninditaBasu** [comment]
Hi @lena-larionova 
May I take up this issue? I am a writer who lives and breathes style guides, and I'd love to contribute, if I may, for the 2021 hackathon.

**Comment by lena-larionova** [comment]
Hi @AninditaBasu, thanks for your interest in contributing to our docs! I've assigned this issue to you now, all yours.

**Comment by AninditaBasu** [comment]
Hi @lena-larionova, I raised an MR: https://github.com/Kong/docs.konghq.com/pull/3241 

🙏🏽 Please review

**Comment by falondarville** [comment]
[#3241](https://github.com/Kong/docs.konghq.com/pull/3241) has been merged! Thank you so much, @AninditaBasu!

**Comment by AninditaBasu** [comment]
🤸🏽‍♀️ 💃🏽
