### ISSUE TITLE
Admission Controller self-signed cert requires SAN

### ISSUE THREAD

**Issue by chazdnato** [Kong/docs.konghq.com#3211]
### Where is the problem?

https://docs.konghq.com/kubernetes-ingress-controller/1.3.x/deployment/admission-webhook/

### What happened?

When following the instructions (or downloading the code from `https://bit.ly/install-kong-admission-webhook`), I get the following error when any call touches the admission controller:

```
Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "validations.kong.konghq.com": Post "https://kong-validation-webhook.kong.svc:443/?timeout=10s": x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0
```

### What did you expect to happen?

This error is a result of how the SSL certificate is created:

```
openssl req -x509 -newkey rsa:2048 -keyout tls.key -out tls.crt -days 365  \
  -nodes -subj "/CN=kong-validation-webhook.kong.svc"
```

The fix is to add an alternative name:
```
openssl req -x509 -newkey rsa:2048 -keyout tls.key -out tls.crt -days 365  \
  -addext "subjectAltName = DNS:kong-validation-webhook.kong.svc" \
  -nodes -subj "/CN=kong-validation-webhook.kong.svc"
```

NOTE: The default `openssl` on a Mac is `LibreSSL 2.8.3` which currently does not support `-addext` (needs LibreSSL `3.1.0` or higher). Mac users should be instructed to use `OpenSSL` via brew or equivalent.

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by lena-larionova** [comment]
@Kong/team-k8s Can you take a look at this issue and verify that the fix is one we should document?

**Comment by rainest** [comment]
@lena-larionova the `-addext` suggestion is valid and is what we should add to docs. Up to you whether or not it makes sense to include a disclaimer for OS X `openssl` tool version info or not--hopefully OS X bumps their default toolset soonish, but I'm not a Mac person and don't know what timelines for that are/typical dev environment expectations around installing newer versions of TLS utils.

**Comment by rainest** [comment]
Came across this while reviewing old issues and realized that it was still open, but the docs pages actually do use a command that includes SANs, and have (I think) a command that adds them even with the outdated OS X LibreSSL. This issue is actually for the script, which resides in the KIC repo, not docs. Fix for that in https://github.com/Kong/kubernetes-ingress-controller/pull/2394

Closing this in favor of that since I can't auto-close on merge from another repo.
