### ISSUE TITLE
Incorrect heading level in documentation for OAuth 2.0 Authentication plugin 

### ISSUE THREAD

**Issue by vaughnbuttiw** [Kong/docs.konghq.com#3214]
### Where is the problem?

https://docs.konghq.com/hub/kong-inc/oauth2/#client-credentials

### What happened?

It looks to me that the heading levels for https://docs.konghq.com/hub/kong-inc/oauth2/#authorization-code and https://docs.konghq.com/hub/kong-inc/oauth2/#client-credentials are such that "Authorization Code" _is part of_ "Client Credentials".

By my understanding this is wrong.

### What did you expect to happen?

I expect the headings for "Client Credentials" and "Authorization Code" to be at the same level.

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by vaughnbuttiw** [comment]
I think the "Client Credentials" heading should be dropped to match "Authorization Code"

**Comment by doble-eme** [comment]
Hi 👋  Can I work on this? I'm forking the repo and will submit the PR later if that's ok. I saw the message about the Hackathon on the WtD Slack.

**Comment by ArmanChand** [comment]
Hello @lena-larionova ,
you can assign it to me, I have started working on it

**Comment by lena-larionova** [comment]
@doble-eme , looks like you ended up working on it, so it's yours 😄 
@ArmanChand , apologies, but looks like @doble-eme got there first.

**Comment by lena-larionova** [comment]
Closing, this is completed.
