### ISSUE TITLE
 the stable/prometheus and stable/grafana helm charts repo are deprecated

### ISSUE THREAD

**Issue by hesmoh** [Kong/docs.konghq.com#3226]
Hi everybody!

### Where is the problem?

https://docs.konghq.com/kubernetes-ingress-controller/1.3.x/guides/prometheus-grafana/

### What happened?

I want to monitor my `kong/kubernetes-ingress-controller` with `prometheus` and `grafana`.
in the documentaion of `KIC` they did this using `helm` , but the problem is helm charts of `prometheus` and `grafana` used in the installation guide are **DEPRECATED**.

### What did you expect to happen?

the guide is using deprecated `Prometheus` components and should be updated

### Code of Conduct and Community Expectations

- [x] I agree to follow this project's Code of Conduct
- [x] I agree to abide by the Community Expectations

**Comment by lena-larionova** [comment]
@Kong/team-k8s can you please take a look? I checked v2.0 docs ([here](https://kic-v2-beta--kongdocs.netlify.app/kubernetes-ingress-controller/2.0.x/guides/prometheus-grafana/)) and it looks like they refer to the same Helm charts.

**Comment by shaneutt** [comment]
@lena-larionova this is a follow up to this discussion: https://github.com/Kong/kubernetes-ingress-controller/discussions/1827

The long and short is that they _are_ deprecated and while we may have a little bit of runway we need to test and document integrating against other non-deprecated Prometheus deployment mechanisms (such as the Prometheus operator which is linked in the discussion thread).

**Comment by lena-larionova** [comment]
Completed in https://github.com/Kong/docs.konghq.com/pull/3288
