### ISSUE TITLE
Copyedit Sessions plugin documentation

### ISSUE THREAD

**Issue by lena-larionova** [Kong/docs.konghq.com#3239]
### Where is the problem?

https://docs.konghq.com/hub/kong-inc/grpc-web/

### What happened?

The current language is not in alignment with our style guide and contains needless complexity. Additionally, there are some grammatical and formatting errors.

File to edit: https://github.com/Kong/docs.konghq.com/blob/main/app/_hub/kong-inc/session/index.md

**Note:** Only edit content starting at the **Usage** section (line 153 onward), as the content above it is generated.

#### Examples of problems
* "Kong Session **Plugin**" - the word plugin should be lowercase and not bold, and there is no need to keep repeating "Kong" before every use of the plugin name. It's enough to just say "the Session plugin", or even "the plugin" if it makes sense in context.
* Overuse of the present tense ("will") when it should be present tense. For example: 
  "When a new request comes in, and a session is already present, then the Kong Session Plugin **will** attach the ngx.ctx variables"
* Run-on sentences
* Instructions are often in the same sentence as explanations or preambles and should be split out into separate lines. For example, the following text:

   ```
  You can also now verify cookie is attached to the browser session: Navigate to http://localhost:8000/sessions-test, 
  which should return 403 and see the message “So long and thanks for all the fish!”
  ```

  Might become:
  ```
  Navigate to http://localhost:8000/sessions-test to verify your setup. 
   
  If the cookie is attached to the browser session, it should return the 
  code 403 and the message “So long and thanks for all the fish!”.
  ```

### What did you expect to happen?

Clear, simple language in accordance with our style guide.

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by Rutam21** [comment]
@lena-larionova Please assign this issue to me. I would be happy to work on this.

**Comment by lena-larionova** [comment]
Thanks for the interest - it's yours! 😄

**Comment by falondarville** [comment]
Closing out this issue as the PR has been merged.
