### ISSUE TITLE
Feature request: PDF download function in the site

### ISSUE THREAD

**Issue by cuttingedge1109** [Kong/docs.konghq.com#3254]
### Where is the problem?

Hi team.
Thanks for your effort and we've been enjoying kong products. This is not a issue report, just a request for a new feature. I found that there is a github action to generate the pdf files for doc but you know, i cannot run the workflow because of the permission problem.

### What is your suggestion?

It would be helpful if the site has the function to download pdf files.
Or for every release(major or minor), you can run that pdf generating pipeline for all [KONG_DOC_VERSIONS](https://github.com/Kong/docs.konghq.com/commit/366aa8468693d660582d236793b0d303a6dcd884#diff-577d738e6754dd1a1cf4faf1e9182b8032ae3182f9f12b1d8a83d087d4ef1880R5-R11) automatically.

Cheers!

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by cuttingedge1109** [comment]
For now, I want `ce_2.5.x` version.
Thanks.

**Comment by lena-larionova** [comment]
Hi @cuttingedge1109 ! Thanks for logging this feature request. We'll evaluate it with the doc team.

Here's the 2.5 CE doc: https://github.com/Kong/docs.konghq.com/suites/3886833534/artifacts/96837750
Let me know if you have any trouble accessing the link.

**Comment by lena-larionova** [comment]
Closing as we have a process to create PDFs. They are not available to download on demand, but requests for PDFs are rare, so for now we will continue using the current process.
