### ISSUE TITLE
Creating a Contribution guide

### ISSUE THREAD

**Issue by SandipPalit** [Kong/docs.konghq.com#3291]
### Where is the problem?

https://github.com/Kong/docs.konghq.com/

### What happened?

I wanted to contribute to Kong Documentation, but I couldn't find any contribution guide in this repo. Hence I want to create a contribution guide to help the contributors in having a clear idea about how to contribute to Kong docs. Please assign it to me.

### What did you expect to happen?

I expect this repo to have a contributing guide, from where I will get a clear idea about how to contribute and what are the best practices.

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by falondarville** [comment]
Hi @SandipPalit, we have a [Contributing Guide](https://docs.konghq.com/contributing/). When you open up an Issue, it's the first link. 

Feel free to open up any PRs you want for improvements to our existing Contributing Guide.
