### ISSUE TITLE
Enterprise Admin API: Fix broken formatting

### ISSUE THREAD

**Issue by falondarville** [Kong/docs.konghq.com#3313]
### Where is the problem?

https://docs.konghq.com/enterprise/2.5.x/admin-api/db-encryption/

### What happened?

Check out the broken formatting:

- https://docs.konghq.com/enterprise/2.5.x/admin-api/db-encryption/#import-exported-keyring
- https://docs.konghq.com/enterprise/2.5.x/admin-api/db-encryption/#import-key

Both the notes and tables are broken. 

### What did you expect to happen?

For the formatting to not be broken. 

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by lena-larionova** [comment]
Fixed in https://github.com/Kong/docs.konghq.com/pull/3521
