### ISSUE TITLE
Several authentication plugins claim that the "hide_credentials" is optional

### ISSUE THREAD

**Issue by seh** [Kong/docs.konghq.com#3368]
### Where is the problem?

https://docs.konghq.com/hub/kong-inc/basic-auth/#parameters

### What happened?

Recently we enabled the Kong ingress controller's validating admission Webhook to catch problems with our _Kong(Cluster)?Plugin_ objects. For [several authentication-related plugins that define a similar "config.hide_credentials" field](https://github.com/Kong/kong/search?l=Lua&q=hide_credentials), [the documentation claims](https://docs.konghq.com/hub/kong-inc/basic-auth/#parameters) that the parameter is optional, and notes a default value. However, as of Kong/kong#6785, these parameters are required.

It's odd that they still define a default value, even though they're required. Kong accepts plugins that lack this "config.hide_credentials" field, but the validating Webhook catches the schema violation and rejects such candidate plugins. This creates an odd situation for us, where we get rejected by the Webhook, but if we disable the Webhook, the plugins appear to work well enough.

### What did you expect to happen?

The documentation should indicate that these parameters are required, not optional.

Ideally, Kong would also reject submitted plugins that lack these required fields.

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by lena-larionova** [comment]
Thanks for catching this issue! I'll update the doc based on these changes.

For the code changes, please go ahead and make the suggestion in the kong/kong code repo (unless you already have 😄 ) .

**Comment by seh** [comment]
> For the code changes, please go ahead and make the suggestion in the kong/kong code repo

Can you clarify what you mean by "the code changes?" Are you referring to this suggestion of mine?

> Ideally, Kong would also reject submitted plugins that lack these required fields.

**Comment by lena-larionova** [comment]
Yes, that's right. Based on this comment:

> Kong accepts plugins that lack this "config.hide_credentials" field, but the validating Webhook catches the schema violation and rejects such candidate plugin

This suggestion sounds like a code change, unless I'm misunderstanding the problem: 

> Ideally, Kong would also reject submitted plugins that lack these required fields.

Either Kong shouldn't accept plugins lacking this field, or the Webhook should be configurable to understand the situations where it _doesn't_ count as a schema violation (if those situations exist). 

However, the docs team aren't the best people to determine that, hence the suggestion to reach out in the source code repo 😄 .

**Comment by seh** [comment]
Please see Kong/kong#8093.

**Comment by lena-larionova** [comment]
Docs updated in https://github.com/Kong/docs.konghq.com/pull/3408.
