### ISSUE TITLE
Missing Kong command in the docker run merged documentation (Enterprise and OSS)

### ISSUE THREAD

**Issue by jdevillard** [Kong/docs.konghq.com#3384]
### Where is the problem?

https://docs.konghq.com/gateway/2.6.x/install-and-run/docker/

### What happened?

The instruction to execute the Db migration is incorrect : 

```
docker run --rm --network=kong-net \
  -e "KONG_DATABASE=postgres" \
  -e "KONG_PG_HOST=kong-database" \
  -e "KONG_PG_PASSWORD=kong" \
  -e "KONG_PASSWORD={PASSWORD}" \
  kong migrations bootstrap
```
return /docker-entrypoint.sh: line 57: exec: migrations: not found

### What did you expect to happen?

The right command should be : 

```
docker run --rm --network=kong-net \
  -e "KONG_DATABASE=postgres" \
  -e "KONG_PG_HOST=kong-database" \
  -e "KONG_PG_PASSWORD=kong" \
  -e "KONG_PASSWORD={PASSWORD}" \
  kong kong migrations bootstrap
```

and same for the Entreprise command

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by falondarville** [comment]
@jdevillard thank you for opening this issue! I'll look into this and update.

**Comment by falondarville** [comment]
I have created an internal task for this. I was able to replicate this issue.

I'm going to add a text input for the second `kong` in `kong kong migrations bootstrap`.

**Comment by falondarville** [comment]
Closing out as this has been resolved. Thank you again, @jdevillard!
