### ISSUE TITLE
When not using the latest documentation left side bar links are out of step.

### ISSUE THREAD

**Issue by rkazak** [Kong/docs.konghq.com#3450]
### Where is the problem?

left side bar links are pointing to latest docs when they should be based off the version being referenced.
<img width="461" alt="Screen Shot 2021-12-02 at 11 54 32 AM" src="https://user-images.githubusercontent.com/3156268/144493344-60749029-5b8d-4e5b-a5bc-0dee61b56311.png">

As you can see from the screenshot I have version 2.3.X select but the links below point to the latest version (atm 2.6.x).

### What is your suggestion?

This is a bug IMHO.
Fix up the references to be relative to the version selected at the top.
This should happen so that relevant information is provided.

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by rkazak** [comment]
Update: Some of the links actually do point to the right version - so this must be a typo/bug

**Comment by lena-larionova** [comment]
@rkazak this was a side-effect of how the "getting started guide" used to be generated when the Gateway docs were split. We had a fair number of odd versioning link issues that we have now resolved with 2.6.x.

I'll update the old Gateway links, but in general, we don't normally backport too many fixes to older doc versions.
