### ISSUE TITLE
Okta setup steps

### ISSUE THREAD

**Issue by rkazak** [Kong/docs.konghq.com#3475]
### Where is the problem?

https://docs.konghq.com/enterprise/2.3.x/plugins/oidc-use-case/, https://docs.konghq.com/gateway/2.6.x/configure/auth/oidc-okta/

### What happened?

I wanted to follow the setup instructions for Okta but the screen shots on these pages don't match what I see on the Okta developer site.

### What did you expect to happen?

Should be able to follow these instructions to complete the task.

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by lena-larionova** [comment]
Thanks for calling this out, we're aware of the issues here. There's already a PR in progress: https://github.com/Kong/docs.konghq.com/pull/3464

Can you try to walk through the process using the draft here, and provide any feedback if you run into issues?

This will be published with Gateway 2.7.

**Comment by lena-larionova** [comment]
Resolved in #3464.
