### ISSUE TITLE
404 on link selection!

### ISSUE THREAD

**Issue by rkazak** [Kong/docs.konghq.com#3487]
### Where is the problem?

https://docs.konghq.com/gateway/2.6.x/get-started/comprehensive/dev-portal/

### What happened?

Selecting the link below ( "Managing Access" ) returns a 404. 

```
https://docs.konghq.com/gateway/2.6.x/developer-portal/administration/
```

### What did you expect to happen?

get the requested page.

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by rkazak** [comment]
This also happens with the link "Configuring the Dev Portal",
```
https://docs.konghq.com/gateway/2.6.x/developer-portal/configuration/
```

**Comment by falondarville** [comment]
Thank you, I will look into this!
