### ISSUE TITLE
Incorrect format mentioned in declarative file DBless start

### ISSUE THREAD

**Issue by ShubhamPalriwala** [Kong/docs.konghq.com#3504]
### Where is the problem?

The code snippet mentioned for the Database-less start on [/gateway/2.7.x/install-and-run/ubuntu/](https://docs.konghq.com/gateway/2.7.x/install-and-run/ubuntu/) under the 
[Using a YAML Declarative File](https://docs.konghq.com/gateway/2.7.x/install-and-run/ubuntu/#using-a-yaml-declarative-config-file) is in the incorrect format as running in the given format:
```yml
database = off
declarative_config = /home/shubham/Desktop/serluar/kong.yml
```
gives the folowing output:
![image](https://user-images.githubusercontent.com/55556994/146536662-8a36e9c2-b0ba-4b83-a8fe-0c6de0a345c4.png)

### What is your suggestion?

However, by fixing the yml input to:
```yml
database = off
declarative_config: /home/shubham/Desktop/serluar/kong.yml
```
starts Kong successfully and shows the following output:
![image](https://user-images.githubusercontent.com/55556994/146536833-9039ea77-1138-40f4-b9de-9ef6333836cf.png)

It is mentioned to **open a PR directly if you know the fix** but this is my first time trying out Kong hence would like to confirm this bug with the community to understand if I'm doing something wrong.
I can open a small PR fixing this wherever this is occurring for now once approved by the maintainers

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by lena-larionova** [comment]
Hi @ShubhamPalriwala ! Thanks for logging this issue. Please take a look at the info right before that section, which says:

> Second, you must configure Kong Gateway using the `kong.conf` configuration file so it is aware of your declarative configuration file.
> Set the database option to off and the declarative_config option to the path of your `kong.ym` file as in the following example

That is, you need to set:
```
database = off
declarative_config = /home/shubham/Desktop/serluar/kong.yml
```
In `kong.conf`, not `kong.yml`, and point to your new `kong.yml`.

I agree that the formatting here is confusing though, so we can look into fixing improving that to avoid confusion in the future.
