### ISSUE TITLE
broken image in kongmap plugin page despite correct markdown syntax

### ISSUE THREAD

**Issue by nikirago** [Kong/docs.konghq.com#3514]
### Where is the problem?

https://docs.konghq.com/hub/yesinteractive/kongmap/

### What happened?

Markdown looks correct but first image on docs page is not rendering. Other images showing correctly with same markdown syntax.
![brokenimage](https://user-images.githubusercontent.com/35073914/147947414-69be5148-6031-4aa1-80f2-1c76c4ecf5f3.png)

### What did you expect to happen?

Image to show.

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by lena-larionova** [comment]
Hi @nikirago! I'm guessing this must have been a page load issue - if you go to the page and refresh it again, the image loads fine: https://docs.konghq.com/hub/yesinteractive/kongmap/

We do occasionally have issues with images not loading quite right on the site, something to look into. But it always works after a refresh.

**Comment by nikirago** [comment]
Thanks @lena-larionova . Issue was that I didn't accept all cookies from the doc site, so for whatever reason wouldn't load that image until I did so (only had strictly necessary cookies enabled). Accepting all fixed it on all browsers.

**Comment by lena-larionova** [comment]
🤔  this is odd. I'll take it up with the Web team.

**Comment by lena-larionova** [comment]
@nikirago can you try disabling cookies again and see if it works? There were some adjustments made yesterday that _should've_ fixed this issue.
