### ISSUE TITLE
No kong.conf.default reference in macOS guide

### ISSUE THREAD

**Issue by Korboh** [Kong/docs.konghq.com#3529]
### Where is the problem?

https://docs.konghq.com/gateway/2.7.x/install-and-run/macos/

### What happened?

After installing kong (brew install kong), the guide tells you to use the 'kong.conf' file. There is no reference to any 'kong.conf.default' file, so it remains unclear, how the 'kong.conf' file looks like.

### What did you expect to happen?

I expected either a 'kong.conf.default' file in '/etc/kong/' or a example 'kong.conf' file in the macOS documentation

### Code of Conduct and Community Expectations

- [x] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by mheap** [comment]
This seems to be resolved as there's a link to `kong.conf.default` on the page now
