### ISSUE TITLE
Additional information to be added to Vault-mTLS configuration

### ISSUE THREAD

**Issue by scottslowe** [Kong/docs.konghq.com#3545]
### Where is the problem?

https://docs.konghq.com/mesh/1.5.x/features/vault/

### What happened?

I was looking for information on configuring Vault-mTLS integration, but ended up having to open a thread in Slack to get the necessary details. #3541 helps somewhat, but there are still a couple details that IMO would be worth adding:

1. We should document that the `tls.caCert.secret` should be stored in the "kong-mesh-system" namespace and be labeled with the name of the mesh to which it applies (in the format `kuma.io/mesh: <mesh-name>`.
2. We should document that the token found in `auth.token.secret` should also be stored in the "kong-mesh-system" namespace. If there are labeling requirements (it's labeled in my environment, but I don't know if the label is required) then we should include those as well. If this needs to be set as a Kuma secret (`type: system.kuma.io/secret`), then that also should be documented.

I'm happy to submit a PR to help with adding these details, if desired.

### What did you expect to happen?

The documentation for configuring Vault-mTLS integration should have had all the necessary information for configuring this functionality.

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by michaelbeaumont** [comment]
> 1. We should document that the tls.caCert.secret should be stored in the "kong-mesh-system" namespace and be labeled with the name of the mesh to which it applies (in the format kuma.io/mesh: <mesh-name>.
> 2. We should document that the token found in auth.token.secret should also be stored in the "kong-mesh-system" namespace. If there are labeling requirements (it's labeled in my environment, but I don't know if the label is required) then we should include those as well. If this needs to be set as a Kuma secret (type: system.kuma.io/secret), then that also should be documented.

I agree, it's not clear at the moment that this is a "Kong Mesh secret" thing. We do however have [(Kuma) docs on those secrets](https://kuma.io/docs/1.4.0/security/secrets/), so we should link there as well as include a short hint on this page.

**Comment by scottslowe** [comment]
Also, under step 4, we advise the reader to use `jq` to parse the results of the `vault token create` command to show only the returned token. I found that Vault will in some cases return a token even if there is an error; for example, if the policy doesn't exist, Vault will still return a token. (The token won't work as expected.) It may be helpful to tell readers that the use of `jq` is an optional thing, so that errors are properly exposed.

**Comment by lena-larionova** [comment]
@scottslowe Thanks for calling this out. You're welcome to go ahead and make a PR with these changes, the help is always appreciated.

**Comment by scottslowe** [comment]
@michaelbeaumont If you have time, can you have a look at the related PR to ensure that the updated wording is accurate/correct?
