### ISSUE TITLE
cluster_telemetry_server_name missing from the configuration reference page

### ISSUE THREAD

**Issue by srb3** [Kong/docs.konghq.com#3575]
### Where is the problem?

https://docs.konghq.com/gateway/2.7.x/reference/configuration/#hybrid-mode-data-plane-section

### What happened?

For PKI mode clustering there is an option to set the expected cluster_telemetry_server_name, however this setting is not documented in the configuration reference page

### What did you expect to happen?

In the hybrid-mode-data-plane-section we should document the cluster_telemetry_server_name setting

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by lena-larionova** [comment]
This is now documented: https://docs.konghq.com/gateway/3.1.x/reference/configuration/#cluster_telemetry_server_name
