### ISSUE TITLE
Conflict occurred when creating an Upstream.

### ISSUE THREAD

**Issue by M-Yamashita01** [Kong/docs.konghq.com#3601]
### Where is the problem?

https://docs.konghq.com/gateway/2.7.x/get-started/comprehensive/load-balancing/

### What happened?

When we ran the following curl command written in the Configure Upstream Services section, we received the following 409 conflict status responses.

```
❯ curl -i -X POST http://localhost:8001/upstreams \
--data name=upstream 
HTTP/1.1 409 Conflict
Date: Fri, 28 Jan 2022 03:51:20 GMT
Content-Type: application/json; charset=utf-8
Connection: keep-alive
Access-Control-Allow-Origin: *
Content-Length: 139
X-Kong-Admin-Latency: 73
Server: kong/2.7.0

{"fields":{"name":"upstream"},"name":"unique constraint violation","message":"UNIQUE violation detected on '{name=\"upstream\"}'","code":5}
```

Kong Version: 2.7.0

We changed the value of `data` arguments from `upstream` to `upstream-service` and ran the curl again, and it worked.
We think the same problem probably occurs when using Kong Manager or decK(YAML).

### What did you expect to happen?

We think the problem occurs because Upstream named `upstream` already exists.
Therefore we think we change the value of `data` arguments, it will work correctly.
(For example: change from `upstream` to `upstream-service`)

If there are no problems, we will create Pull Request.

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by lena-larionova** [comment]
Thanks for  catching this issue. Looks like you're right, `upstream` is a reserved entity name.

I'll fix the error, as it appears throughout many versions of the guide - and occasionally, it doesn't conflict (I just tested it in my local, and the upstream was created). But to avoid any potential errors like the one you ran into, I'll make sure we aren't using a reserved name.

**Comment by M-Yamashita01** [comment]
Thank you for your response.
Please fix it.
We will close this issue.
