### ISSUE TITLE
Enabling postgres db missing some required steps.

### ISSUE THREAD

**Issue by rkazak** [Kong/docs.konghq.com#3648]
### Where is the problem?

https://docs.konghq.com/gateway/2.7.x/install-and-run/ubuntu/

### What happened?

While the customer was following the instructions to install on a host, centos in my case, he found that Kong failed to start.

### What did you expect to happen?

Kong should have started.

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by rkazak** [comment]
As the postgres setup is common to all host style platform installs this issue is common to all.  The instructions for setting up   a postgres instance are missing a few required commands.

As there is no single way to do this I am listing here the extra steps and leave it to you to decide what is best. For example creating the user can all be done via SQL but I used the `createuser` tool from postgres... I would suggest SQL is the better option.  Also I made the `kong` user have the same privs as I discovered on my test instance, which is basically the same as the `postgres` user.

```
[root@ip-172-30-1-33 centos]# sudo /usr/pgsql-14/bin/postgresql-14-setup initdb
Initializing database ...
OK


As the postgres user ( I am just matching the user with my container instance setup );


-bash-4.2$ createuser --interactive
Enter name of role to add: kong
Shall the new role be a superuser? (y/n) y
-bash-4.2$

-bash-4.2$ plsql
postgres=# create database kong owner kong;
CREATE DATABASE

postgres=# alter user kong with replication bypassrls;
ALTER ROLE

postgres=# alter user kong with password 'kong';
ALTER ROLE

postgres=# \q

Then as the kong user and do the following

[root@ip-172-30-1-33 centos]# su - kong
Last login: Fri Feb 4 01:45:35 UTC 2022 on pts/0

-sh-4.2$ kong migrations bootstrap
Bootstrapping database...
migrating core on database 'kong'...
core migrated up to: 000_base (executed)
...
enterprise.response-transformer-advanced migrated up to: 001_1500_to_2100 (executed)
85 migrations processed
85 executed
Database is up-to-date


That should now have setup the postgres database ready for Kong.
```

**Comment by mheap** [comment]
The URL above has been updated with `CREATE USER kong WITH PASSWORD 'super_secret'; CREATE DATABASE kong OWNER kong;` since this issue was created
