### ISSUE TITLE
Plugin Documentation lacks any reference for deletion

### ISSUE THREAD

**Issue by therealgambo** [Kong/docs.konghq.com#368]
I've just opened the PR #367 for documenting how to delete a JWT credential since it was not covered, upon doing this I've had a quick look through most of the plugins and they all seem to lack documentation (where applicable) on how to delete a resource that they provide.

**Comment by jeremyjpj0916** [comment]
Was reading over the Oauth2.0 credentials as well and began thinking the same thing, no info on what path to call the -X DELETE on to remove creds from a consumer.

**Comment by falondarville** [comment]
PR 365 has been merged: https://github.com/Kong/docs.konghq.com/pull/367

Auth 2.0 revoke access tokens: https://docs.konghq.com/hub/kong-inc/oauth2/#viewing-and-invalidating-access-tokens
