### ISSUE TITLE
Kong Ingress docs refer to wrong/different annotation to what is shown in diagrams

### ISSUE THREAD

**Issue by erSitzt** [Kong/docs.konghq.com#3699]
### Where is the problem?

https://docs.konghq.com/kubernetes-ingress-controller/2.1.x/concepts/custom-resources/#kongingress

### What happened?

The docs say:

Once a KongIngress resource is created, you can use the **configuration.konghq.com** annotation to associate the KongIngress resource with an Ingress or a Service resource:

But the diagram shows
<img width="712" alt="image" src="https://user-images.githubusercontent.com/1625376/155202294-8830dc27-6b81-4fd7-a5ad-782fc0f92b3b.png">

### What did you expect to happen?

Shouldn't it say "use **konghq.com/override** annotation" then ?

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by erSitzt** [comment]
Looking at some examples i found it looks like at least in 2020 **configuration.konghq.com** was used ?
I'm a little confused, which one is correct ?

Found here 
https://kubernetes.io/blog/2020/03/18/kong-ingress-controller-and-istio-service-mesh/
and here
https://discuss.konghq.com/t/kong-ingress-controller-istio-service-mesh-doesnt-support-global-mtls/5971/8

**Comment by anup-krai** [comment]
Kong Ingress Annotation is corrected in doc.

**Comment by Guaris** [comment]
Thank you for reporting this!
