### ISSUE TITLE
Compatibility statement in Kafka Log doc 

### ISSUE THREAD

**Issue by rkazak** [Kong/docs.konghq.com#3704]
### Where is the problem?

https://docs.konghq.com/hub/kong-inc/kafka-log/0.2.x.html

### What happened?

A customer running 2.4.1.1 and they would like to use the Kafka log plugin, and specifically the “config.security.ssl” feature. On the plugin page it lists it as compatible with 2.4 however 2.4.1.1 has version ‘ KafkaLogHandler.VERSION = “0.1.1" ’ - and the feature they are interested in was implemented in 2.6.0 - so is the page misleading?

### What did you expect to happen?

I am not sure, if that specific feature was not the point in question then it 'would' be compatible?  TBH I am not sure what the best way to handle representing this type of information.

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by lena-larionova** [comment]
Closing as we no longer maintain docs for versions before 2.6.
