### ISSUE TITLE
Sentence Fluency

### ISSUE THREAD

**Issue by Chimi-S** [Kong/docs.konghq.com#3774]
### Where is the problem?

https://docs.konghq.com/gateway/2.8.x/get-started/comprehensive/prepare/

### What happened?

When I read through the document of Verify the Kong Gateway configuration I was stuck, I found that space between the word of "sure".
![document](https://user-images.githubusercontent.com/48045494/159419908-37b7ff55-bb6b-4fa9-822d-38b0801f1947.png)

### What did you expect to happen?

 While reading I expected sentences to be fluent. 

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by lena-larionova** [comment]
FIxed in https://github.com/Kong/docs.konghq.com/pull/3775.
