### ISSUE TITLE
Writing tests page has faulty information

### ISSUE THREAD

**Issue by Fake51** [Kong/docs.konghq.com#3780]
### Where is the problem?

https://docs.konghq.com/gateway/2.8.x/plugin-development/tests/

### What happened?

I wanted information about writing tests for a plugin in my own repo. The doc has details on how to do this, but they fail very short.

_If you are writing your plugin in your own repository, you will need to copy the following files until the Kong testing framework is released:_

    bin/busted: the busted executable running with the resty-cli interpreter
    spec/helpers.lua: helper functions to start/stop Kong from busted
    spec/kong_tests.conf: a configuration file for your running your test Kong instances with the helpers module

_Assuming that the spec.helpers module is available in your LUA_PATH, you can use the following Lua code in busted to start and stop Kong_

Copying these files into your repo doesn't allow you to run anything - you'll be missing a ton of kong files, it seems.

### What did you expect to happen?

I expected to get updated details of how to write a plugin in my own repo.

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by lena-larionova** [comment]
@Kong/team-core looks like we're missing some content in our plugin development testing doc. Should we instead direct users to the performance testing framework doc (https://docs.konghq.com/gateway/2.8.x/plan-and-deploy/performance-testing-framework/), or is there something we clarify in the [plugin dev doc](https://docs.konghq.com/gateway/2.8.x/plugin-development/tests/) ?

**Comment by lena-larionova** [comment]
We have published a new guide a few months ago that covers testing in much more detail: https://docs.konghq.com/gateway/latest/plugin-development/get-started/testing/
