### ISSUE TITLE
Please update the "Version Support for Kong Mesh" table to include the current releases

### ISSUE THREAD

**Issue by rkazak** [Kong/docs.konghq.com#3782]
### Where is the problem?

https://docs.konghq.com/konnect-platform/support-policy/#version-support-for-kong-gateway-enterprise

### What happened?

Looking for information about recent Kong Mesh releases.

### What did you expect to happen?

We should have the Kong Mesh table updated to include all releases - in a similar fashion to the Gateway table.

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by mheap** [comment]
Already done
