### ISSUE TITLE
incorrect host name 

### ISSUE THREAD

**Issue by NawafAlsuwailem** [Kong/docs.konghq.com#3795]
### Where is the problem?

https://docs.konghq.com/gateway/2.8.x/get-started/comprehensive/load-balancing/

### What happened?

the mentioned host in step number 12:
- Change the Host field to **upstream**, then click Update.
 should be **example_upstream**, instead of **upstream** only. 

### What did you expect to happen?

load-balancer should've worked, but since the hostname was incorrect it wasn't able to local the required host/upstream  

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by lena-larionova** [comment]
Nice catch, this was an oversight when we changed the name. Fixing now.
