### ISSUE TITLE
In 2.8 under Dev portal ->  Application Registration - Menu items point to the same page.

### ISSUE THREAD

**Issue by rkazak** [Kong/docs.konghq.com#3847]
### Where is the problem?

https://docs.konghq.com/gateway/2.8.x/developer-portal/

### What happened?

I selected both the items in the screenshot and both took me to the same page. (So we have dropped a page? )

<img width="372" alt="Screen Shot 2022-04-15 at 18 00 18" src="https://user-images.githubusercontent.com/3156268/163655926-c71c3dba-1700-476a-886a-6620f243127b.png">

### What did you expect to happen?

Get the correct page :)

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by rkazak** [comment]
Please check against 2.7 which seems to be correct.

**Comment by lena-larionova** [comment]
Nice catch - human error caused this one. Fixing, and we'll have checks in place to make sure we don't do it again.
