### ISSUE TITLE
Ubuntu download curl command returns 404

### ISSUE THREAD

**Issue by gkarabotsos** [Kong/docs.konghq.com#3900]
### Where is the problem?

https://docs.konghq.com/gateway/2.8.x/install-and-run/ubuntu/

### What happened?

Tried to run the curl command to download the package and failed with 404.  This is the command: `curl -Lo kong-enterprise-edition-2.8.1.0.all.deb "https://download.konghq.com/gateway-2.x-ubuntu-$(lsb_release -cs)/pool/all/k/kong-enterprise-edition/kong_2.8.1.0_all.deb"`

### What did you expect to happen?

Download the package

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by gkarabotsos** [comment]
Of course: 
```
georgek@montreal:~$ lsb_release -cs
jammy
georgek@montreal:~$ uname -a
Linux montreal 5.15.0-27-generic #28-Ubuntu SMP Thu Apr 14 04:55:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by gkarabotsos** [comment]
Same result for focal:

**Comment by hutchic** [comment]
we don't currently release an official jammy package (though focal **should** be compatible) and looks like the Kong Enterprise package has a typo in the package name sorry about that.

The package name needs a `s/kong/kong-enterprise-edition/g` ie the actual url is 

snip...ubuntu-focal/pool/all/k/kong-enterprise-edition/kong-enterprise-edition_2.8.1.0_all.deb not
snip...ubuntu-focal/pool/all/k/kong-enterprise-edition/kong_2.8.1.0_all.deb

https://download.konghq.com/gateway-2.x-ubuntu-focal/pool/all/k/kong-enterprise-edition/ might be of benefit until I fix that typo
