### ISSUE TITLE
example certificates expired in mtls guide page

### ISSUE THREAD

**Issue by randmonkey** [Kong/docs.konghq.com#3941]
same as kong/kubernetes-ingress-controller#2493
### Where is the problem?

https://docs.konghq.com/kubernetes-ingress-controller/2.3.x/guides/using-mtls-auth-plugin/#main

### What happened?

CA certificate and client certificate are expired in the guide page of mtls-auth plugin: https://docs.konghq.com/kubernetes-ingress-controller/2.3.x/guides/using-mtls-auth-plugin/#main
This makes users fail to try `mtls-auth` plugin when follow the guide.

### What did you expect to happen?

Users can create an ingress in KIC by following each step of this page: https://docs.konghq.com/kubernetes-ingress-controller/2.3.x/guides/using-mtls-auth-plugin/#main

### Possible solutions

3 solutions would be possible:
(1) replace with example certificates with new certs, while they would expire after a duration. This solution needs to periodically update the certs, or use certs with very long duration.
(2) use commands to generate CA certificates and client certificates in guide page, like this
```
## Create a self-signed certificate as CA certificate
$ openssl req -x509 -newkey rsa:4096 -keyout ca-key.pem -out ca-cert.pem -sha256 -days 365 -nodes
......
## Create client certs and keys
$ openssl req -newkey rsa:2048 -nodes -days 365  -keyout client-key.pem -out client-req.pem
openssl x509 -req -days 365 -set_serial 01 -in ./client-req.pem -out client-cert.pem -CA ~/test-certs/ca-cert.pem -CAkey ~/test-certs/ca-key.pem
```
This might be a noticeable change for the page, and might be harder for user to follow the guide to operate.
(3) (by @pmalek )add a Github workflow that would run on a schedule (e.g. every 90 days?) which would create a PR against the docs repo with the newly generated certs. 

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by rainest** [comment]
These should be fine to keep as-is. Nobody should be actually using our example certificates in general, and it's not possible for readers to issue certificates from the example CA (we intentionally don't provide the key). The example here is just to show what the end result YAML should look like after you paste in your actual CA's PEM-encoded cert.

**Comment by randmonkey** [comment]
How about adding some tips on the guide page to tell users not to directly use the certificates in examples? like this 
```
Tip: The examples here only shows the format of yaml. DO NOT directly use the certificates here.
You can use existing available CA certificates, or generate self-signed certificates for testing.
```

**Comment by rainest** [comment]
I'd say use boldface instead of "Tip:" at the beginning, it'll stand out more when scanning visually. Some other suggestions for clarification but I care less about those:

```
**The examples here are only to show the certificate Secret YAML format. DO NOT directly use the certificates here.
You can use existing available CA certificates, or generate self-signed certificates for testing.**
```

We could optionally provide a general-purpose guide (probably in the Gateway section rather than the controller section--we'd only link to it here) for creating and using a self-signed CA. https://github.com/cloudflare/cfssl is a good tool for this, though you can probably find a better guide somewhere to draw inspiration from than their Github readme.
