### ISSUE TITLE
How to wrap lines when adding custom plug-in names?

### ISSUE THREAD

**Issue by 1798972** [Kong/docs.konghq.com#4047]
### Where is the problem?

https://docs.konghq.com/gateway/2.8.x/plugin-development/file-structure/

### What happened?

If we have a lot of plugins,It is very inconvenient to view.
How to wrap lines when adding custom plug-in names?
![image](https://user-images.githubusercontent.com/49218070/175306179-58326d26-e917-4dce-a473-3dffe309dd75.png)

### What did you expect to happen?

like this:

plugins = bundled,
my-custom-plugin1,
my-custom-plugin2
...

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by mheap** [comment]
Unfortunately I don't believe this is possible
