### ISSUE TITLE
Enhance local docs build instructions

### ISSUE THREAD

**Issue by usrbinkat** [Kong/docs.konghq.com#4235]
### Where is the problem?

https://github.com/Kong/docs.konghq.com/blob/main/docs/platform-install.md

### What happened?

While attempting to install dependencies for building the docs site locally I encountered multiple issues which were resolved with the following steps:
```
sudo gem install liquid-c -v '4.0.0' --source 'https://rubygems.org/' -- --with-cflags=\"-Wno-compound-token-split-by-macro\"
sudo brew link ruby --force
bundle exec jekyll build -c jekyll-dev.yml
```

### What did you expect to happen?

Expected local dependency prep instructions to satisfy the requirements of `make install && make run`

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by mheap** [comment]
The brew link step shouldn't be required if you're using rbenv
