### ISSUE TITLE
Incorrect information provided re minikube

### ISSUE THREAD

**Issue by rkazak** [Kong/docs.konghq.com#4250]
### Where is the problem?

https://docs.konghq.com/kubernetes-ingress-controller/2.5.x/deployment/kong-enterprise/

### What happened?

The Note mentions this

"If you are running Minikube, you will not get an external IP address."

which is not strictly true, as a correctly configured minikube env will.

```
| minikube4 | docker    | docker  | 192.168.49.2  | 8443 | v1.24.3  | Running |     1 | *      |

Test2 /Users/rkazak/minikube/ex1/dev >kubectl get services -n kong
NAME                      TYPE           CLUSTER-IP      EXTERNAL-IP     PORT(S)                      AGE
kong-admin                LoadBalancer   10.96.161.232   192.168.49.10   80:31421/TCP                 2m31s
kong-manager              LoadBalancer   10.96.39.96     192.168.49.11   80:32470/TCP                 2m31s
kong-proxy                LoadBalancer   10.96.226.161   192.168.49.12   80:32405/TCP,443:32508/TCP   2m30s
kong-validation-webhook   ClusterIP      10.106.90.207   <none>          443/TCP                      2m30s
```

### What did you expect to happen?

We should remove that sentence.  Not sure how much we want to document minikube usage, or just point to appropriate pages.

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by mheap** [comment]
@rkazak Are you using MetalLB or similar?

**Comment by afzal442** [comment]
/assign
I tjnk, the above experimentation is done on Minikube cluster without MetalB. If you have large memory set during `minikube start ..`, then you will have everything worked.

**Comment by Rajakavitha1** [comment]
Hi @lena-larionova  can we now mark this issue as closed?

**Comment by lena-larionova** [comment]
@Rajakavitha1 absolutely, thanks for addressing it.
