### ISSUE TITLE
Clarification about PDK & Kong version compatibility.

### ISSUE THREAD

**Issue by JuanMorenoDeveloper** [Kong/docs.konghq.com#4332]
### Where is the problem?

https://docs.konghq.com/gateway/latest/pdk/

### What happened?

The end of the first paragraph says: 

> The PDK is guaranteed to be forward-compatible from its 1.0.0 release and onward.

But the current PDK readme pages said: 

https://github.com/Kong/kong-js-pdk/blob/master/README.md

https://github.com/Kong/kong-python-pdk/blob/master/README.md

> Requires Kong >= 2.3.0. 

So the compatibility statement (1.0.0) is still valid?

### What did you expect to happen?

Get clarification about PDK & Kong version compatibility.

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by lena-larionova** [comment]
@JuanMorenoDeveloper Can you please post this question in the source code repo ([kong/kong](https://github.com/Kong/kong/issues))? This particular doc is automatically generated straight from the code: https://github.com/Kong/kong/blob/master/kong/pdk/init.lua
