### ISSUE TITLE
Vitals with InfluxDB should declare that we don't support SSL connections at this time

### ISSUE THREAD

**Issue by d19dotca** [Kong/docs.konghq.com#4365]
### Where is the problem?

https://docs.konghq.com/gateway/latest/vitals/vitals-influx-strategy/

### What happened?

I had a customer open a support case asking for how to setup Vitals using influxdb as the strategy for SSL endpoint, however we do not support SSL endpoints yet for the external Vitals endpoints, according to FTI-3043. I then realized this should ideally be added to the docs so that we can reference this with customers who may ask this in the future.

### What did you expect to happen?

Hopefully we'd document on this page (and I believe for the Vitals with Prometheus page too) that we only support non-SSL endpoints at this time for Vitals external strategy endpoints.

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by lena-larionova** [comment]
Closing since we deprecated vitals.
