### ISSUE TITLE
Plugin examples use curl-specific feature in non-curl examples

### ISSUE THREAD

**Issue by rainest** [Kong/docs.konghq.com#4383]
### Where is the problem?

https://docs.konghq.com/hub/kong-inc/exit-transformer/

### What happened?

Not sure myself how to provide per-type values for the generated plugin example tabs.

The Kubernetes example for this plugin uses the following:

```
config: 
  functions:
  - @example/my_function.lua
```

Manager instructions include something similar.

The curl instructions use `--data "config.functions=@example/my_function.lua"`. this `=@/path/to/file` syntax is a curl-specific feature that instructs curl to load the file at that path and substitute its contents as the value sent to the server. This does not work in either Kubernetes YAML or in Manager.

Similar examples are likely present in the following also:

```
$ grep -lr "=@" app/_hub                          
app/_hub/kong-inc/mocking/_index.md
app/_hub/kong-inc/mocking/0.1.x.md
app/_hub/kong-inc/serverless-functions/0.2-x.md
app/_hub/kong-inc/serverless-functions/1.0-x.md
app/_hub/kong-inc/serverless-functions/0.1-x.md
app/_hub/kong-inc/serverless-functions/_index.md
app/_hub/kong-inc/serverless-functions/0.3-x.md
app/_hub/kong-inc/upstream-tls/0.35-x.md
app/_hub/kong-inc/upstream-tls/_index.md
app/_hub/kong-inc/jwt/2.1-x.md
app/_hub/kong-inc/jwt/0.1-x.md
app/_hub/kong-inc/jwt/_index.md
app/_hub/kong-inc/exit-transformer/1.3-x.md
app/_hub/kong-inc/exit-transformer/_index.md
app/_hub/kong-inc/mtls-auth/0.36-x.md
app/_hub/kong-inc/mtls-auth/1.3-x.md
app/_hub/kong-inc/mtls-auth/_index.md
app/_hub/kong-inc/response-transformer-advanced/2.1.x.md
app/_hub/kong-inc/response-transformer-advanced/1.5.x.md
app/_hub/kong-inc/response-transformer-advanced/1.3-x.md
app/_hub/kong-inc/response-transformer-advanced/_index.md
```

Though some of those may be curl-only examples.

### What did you expect to happen?

Kubernetes should instead include the function as a multi-line string, e.g.

```
config: 
  functions:
  - |
  local responses = {
    ["Invalid authentication credentials"] = {
      message = "Invalid API key",
    },
  }
  
  return function(status, body, headers)
    if not body or not body.message then
      return status, body, headers
    end
  
    local response = responses[body.message]
  
    body.message = response.message or body.message
    status = response.status or status
    headers = response.headers or headers
  
    return status, body, headers
  end

plugin: exit-transformer
```

As best I recall, for Manager you just paste the file contents into the `config.functions` field, though it may do weird things with spacing.

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by lena-larionova** [comment]
This was fixed during a rework of the plugin hub: https://docs.konghq.com/hub/kong-inc/exit-transformer/how-to/basic-example/
