### ISSUE TITLE
KIC unavailable Helm value

### ISSUE THREAD

**Issue by MalteHei** [Kong/docs.konghq.com#4456]
### Where is the problem?

https://docs.konghq.com/kubernetes-ingress-controller/latest/deployment/overview/

### What happened?

Pretty much every KIC Deployment doc includes instructions for installing via Helm.
These instructions always include `--set ingressController.installCRDs=false` which is not documented in [values.yaml](https://github.com/Kong/charts/blob/main/charts/kong/values.yaml). Also, setting this value does not seem to work, as the usual CRDs are still being created, which might cause some confusion.

### What did you expect to happen?

The argument `--set ingressController.installCRDs=false` installations should be removed from the docs.

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by Rajakavitha1** [comment]
Hi @lena-larionova  can we now mark this issue as closed?
