### ISSUE TITLE
In the rate limiting plugin, service_id is not included in the schema but is listed as semi-optional in docs

### ISSUE THREAD

**Issue by raminkhoshbin** [Kong/docs.konghq.com#4580]
### Where is the problem?

https://docs.konghq.com/hub/kong-inc/rate-limiting/

### What happened?

We tried configuring the rate limiting plugin with limit_by : service and a service_id but got a schema violation ( service_id : "unknown field" ). A try without sending a service_id has worked. Through further investigation, we found no service_id property in the rate-limiting schema.lua
https://github.com/Kong/kong/blob/eecc8758c48e0ec004af20a30750a141789d48b0/kong/plugins/rate-limiting/schema.lua#L62
So there is an inconsistency between docs and code. The rate-limiting schema.lua history shows that service_id was never included as far as we checked (Sep 16, 2019).

### What did you expect to happen?

Based on Kong docs we expected to be able to configure a rate limiting plugin with limit_by: service and service_id property.

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by Benny-Git** [comment]
Created PR to fix this.

Benjamin Bertow [benjamin.bertow@mercedes-benz.com](mailto:benjamin.bertow@mercedes-benz.com), Mercedes-Benz Tech Innovation GmbH

**Comment by Benny-Git** [comment]
Merged, the new documentation should be correct: https://docs.konghq.com/hub/kong-inc/rate-limiting/

Please check, so the issue can be closed.
