### ISSUE TITLE
KIC Prometheus/Grafana guide has a dead link

### ISSUE THREAD

**Issue by pmalek** [Kong/docs.konghq.com#4647]
### Where is the problem?

https://docs.konghq.com/kubernetes-ingress-controller/2.7.x/guides/prometheus-grafana/#install-services

### What happened?

https://docs.konghq.com/kubernetes-ingress-controller/2.7.x/examples/001_multiple-services.yaml is a dead link.

Most likely the intention was to link to https://github.com/Kong/docs.konghq.com/blob/main/src/kubernetes-ingress-controller/examples/001_multiple-services.yaml but for some reason this is not possible (something changed?).

### What did you expect to happen?

The link should not be dead and should link to https://github.com/Kong/docs.konghq.com/blob/main/src/kubernetes-ingress-controller/examples/001_multiple-services.yaml.

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by randmonkey** [comment]
I think we should configure somewhere in the repo to make the link correctly to the file in example. The link is used to download the raw content of the file, but this link https://github.com/Kong/docs.konghq.com/blob/main/src/kubernetes-ingress-controller/examples/001_multiple-services.yaml will return a webpage.
