### ISSUE TITLE
Add KIC information for plugin ordering

### ISSUE THREAD

**Issue by rainest** [Kong/docs.konghq.com#4654]
### Where is the problem?

https://docs.konghq.com/kubernetes-ingress-controller/latest/references/custom-resources/#kongplugin,https://docs.konghq.com/gateway/3.0.x/kong-enterprise/plugin-ordering/get-started/

### What happened?

KIC 2.6 added support for plugin ordering, but we haven't written docs for it yet.

### What did you expect to happen?

The KIC CRD references (https://docs.konghq.com/kubernetes-ingress-controller/latest/references/custom-resources/#kongplugin and https://docs.konghq.com/kubernetes-ingress-controller/latest/references/custom-resources/#kongclusterplugin) show the format of the `Ordering` field in Kong(Cluster)Plugins.

The plugin ordering guide (https://docs.konghq.com/gateway/3.0.x/kong-enterprise/plugin-ordering/get-started/) shows an example KongPlugin resource equivalent to the admin API examples.

Tracked in the docs repo, but will be written by someone from the Kubernetes team.

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by pmalek** [comment]
@rainest Is https://github.com/Kong/docs.konghq.com/pull/4667 everything that we need ? If so can we close this one?
