### ISSUE TITLE
Rename "OS X" to "macOS"

### ISSUE THREAD

**Issue by hishamhm** [Kong/docs.konghq.com#470]
I considered sending a PR for that with a general find-and-replace, but the URL for installation instructions uses "osx" so I'm not sure if it's wise to break that, and there's the `osx.svg` asset that needs updating as well.

**Comment by coopr** [comment]
A good partial fix could be to update to "macOS" in the written portion of the docs, but leave the URL and assets named as they are.

**Comment by coopr** [comment]
@arshadkazmi42 sure, that'd help! Note the comment above that points out that changing URLs and asset names is a little more involved - you could do that, or not, either way, your contribution will be appreciated!

**Comment by arshadkazmi42** [comment]
Created PR.
