### ISSUE TITLE
Supported versions page displays supported version timetable for all products

### ISSUE THREAD

**Issue by randmonkey** [Kong/docs.konghq.com#4955]
### Where is the problem?
- https://docs.konghq.com/gateway/latest/support-policy/  
- https://docs.konghq.com/kubernetes-ingress-controller/latest/support-policy/ 
- https://docs.konghq.com/mesh/latest/support-policy/  

### What happened?

Now the timetable of supported versions of Kong gateway, KIC and Kong mesh are moved into a page in "include", so supported versions of the 3 products could be seen on support policy pages of all 3 products. I do not know if this is expected.

### What did you expect to happen?

support policy page of each product displays only supported version table for the product itself.

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by acgoldsmith** [comment]
Fixed for Gateway and KIC w/ @randmonkey 's PR4956
