### ISSUE TITLE
RBAC admin API endpoints calls are missing "negative" parameter

### ISSUE THREAD

**Issue by vvidovic** [Kong/docs.konghq.com#5114]
### Where is the problem?

https://docs.konghq.com/gateway/3.1.x/production/access-control/enable-rbac/#team-admins-create-team-regular-users

### What happened?

In the "Enabling RBAC" examples for creation of regular users, when filtering access to "/rbac/*" and "/workspaces/*", the "negative=true" parameter is missing.

The following HTTPie requests needs to be updated:
```
http :8001/teamA/rbac/roles/users/endpoints/ endpoint=/rbac/* workspace=teamA actions=* Kong-Admin-Token:n5bhjgv0speXp4N7rSUzUj8PGnl3F5eG
http :8001/teamA/rbac/roles/users/endpoints/ endpoint=/workspaces/* workspace=teamA actions=* Kong-Admin-Token:n5bhjgv0speXp4N7rSUzUj8PGnl3F5eG
```

### What did you expect to happen?

The HTTPie requests should look like:
```
http :8001/teamA/rbac/roles/users/endpoints/ endpoint=/rbac/* workspace=teamA actions=* negative=true Kong-Admin-Token:n5bhjgv0speXp4N7rSUzUj8PGnl3F5eG
http :8001/teamA/rbac/roles/users/endpoints/ endpoint=/workspaces/* workspace=teamA actions=* negative=true Kong-Admin-Token:n5bhjgv0speXp4N7rSUzUj8PGnl3F5eG
```

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by Guaris** [comment]
I believe this issue is solved by https://github.com/Kong/docs.konghq.com/pull/5830 please reopen if that is not the case.
