### ISSUE TITLE
Misstatement

### ISSUE THREAD

**Issue by ysj0226** [Kong/docs.konghq.com#5145]
### Where is the problem?

docs.konghq.com/app/_src/gateway/production/deployment-topologies/hybrid-mode/index.md

### What happened?

In the second paragraph of Fault tolerance, What is described in the text is
This means that the data plane nodes can be stopped even for extended periods of time, and the data plane will still proxy traffic normally. 

### What did you expect to happen?

This means that the _control plane_ nodes can be stopped even for extended periods of time, and the data plane will still proxy traffic normally. 

I am not quite sure, my understanding is that a long shutdown of cp will not have any effect on dp.
However, the document may be intended to tell us that restarting dp after shutdown can still provide stable service.
I'm not sure which one is right. Thank you for your information

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by d19dotca** [comment]
Hi @ysj0226 - I've made the fix in the documentation via the PR #5600. Thank you for pointing out that error in the documentation.

>I am not quite sure, my understanding is that a long shutdown of cp will not have any effect on dp.
However, the document may be intended to tell us that restarting dp after shutdown can still provide stable service.
I'm not sure which one is right. Thank you for your information

To clarify, yes the CP can be shut down for a long period of time without any effect on the DP. The DP will continue to run from its local cached configuration. The DPs load the full configuration from the CP with every update to the CP, so the DP will always run with the latest configuration it is aware of at the time before the CP goes offline. The DP can be restarted and it will still keep the configuration as there's a file locally to it that the configuration is saved to, so it can survive restarts.
