### ISSUE TITLE
`curl --resolve` commands in KIC's guides don't work for minikube's `PROXY_IP`

### ISSUE THREAD

**Issue by czeslavo** [Kong/docs.konghq.com#5200]
### Where is the problem?

https://docs.konghq.com/kubernetes-ingress-controller/2.8.x/guides/getting-started/

### What happened?

A user was trying to complete the [Getting started with KIC](https://docs.konghq.com/kubernetes-ingress-controller/2.8.x/guides/getting-started/) guide having a Minikube Kong setup created following the [Kong Ingress on Minikube](https://docs.konghq.com/kubernetes-ingress-controller/2.8.x/deployment/minikube/) guide. When he got to the point where a route is to be tested with `curl -i http://kong.example/echo --resolve kong.example:80:$PROXY_IP`, the command didn't work.

The reason it couldn't work is the `$PROXY_IP` that he got from the Minikube guide was a full URL (e.g. `http://192.168.99.100:32728`), not just an IP address. It resulted in `curl -i http://kong.example/echo --resolve kong.example:80:http://192.168.99.100:32728` which is invalid.

### What did you expect to happen?

The curl commands in KIC guides that use `--resolve` flag should take into account that the `$PROXY_IP` might be not just an IP address. That could be achieved by replacing `--resolve kong.example:80:$PROXY_IP`s with `-H "Host: kong.example"`. Also changing the `$PROXY_IP` name to better reflect its nature would be advised (e.g. to `$PROXY_URL`).

An alternative would be to enforce the `$PROXY_IP` to always be (as it's named) an IP address (requiring changes in the Minikube guide).

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by Rajakavitha1** [comment]
Hi @czeslavo !! I tried to address the issues in these two PRs after testing and validating. https://github.com/Kong/doc
[minikubeKIC-test.txt](https://github.com/Kong/docs.konghq.com/files/12160202/minikubeKIC-test.txt)
s.konghq.com/pull/5842 and https://github.com/Kong/docs.konghq.com/pull/5844. Please take a look and let me know if any changes need to be made.
