### ISSUE TITLE
Documentation versioning for plugins 

### ISSUE THREAD

**Issue by PGBI** [Kong/docs.konghq.com#529]
Admin API is versioned (ex: https://getkong.org/docs/0.9.x/admin-api ), but not for plugins although some plugins do evolve over time (like the oauth2 one).

As a maintainer of kong-dashboard, it's difficult for me to offer a UI that's compatible with multiple versions of Kong for plugins since I can't find documentations corresponding to older versions of Kong.

**Comment by coopr** [comment]
Solved! Sort of :/

Now that docs for all plugins and integrations have been moved to https://docs.konghq.com/hub/ (woo hoo! See https://konghq.com/blog/welcome-to-the-new-kong-hub/), we've got versioned plugin docs! 

That said... we only have versioned plugin docs for recent versions of Kong Enterprise plugins. Kong plugins currently have un-versioned documentation - they document how the plugin exists in the recent Kong 0.14 release. There is no plan to attempt to generate historical versions of plugin docs - instead, we'll add new plugin version docs going forward.

As such, I'm going to close this issue.
