### ISSUE TITLE
Deck > Konnect 404's

### ISSUE THREAD

**Issue by johnharris85** [Kong/docs.konghq.com#5368]
### Where is the problem?

https://docs.konghq.com/deck/1.19.x/reference/deck_konnect/

### What happened?

404

### What did you expect to happen?

Deck Konnect documentation

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by johnharris85** [comment]
It's linked on the bottom of the top-level Deck page, I wasn't sure what the correct behavior was (as the file still exists in the tree), but it's not in the nav. I'm happy to fix this, will just remove the link to it. PR incoming....

**Comment by lena-larionova** [comment]
After some digging, figured out that they are indeed deprecated, but it doesn't come up when you use the `--help` flag for any `deck konnect` commands. This feels like an oversight 🤔 . And there should probably be some `deprecated` label on them as well (in decK itself, I mean).
