### ISSUE TITLE
Kong Mesh is missing OPA Policy doc

### ISSUE THREAD

**Issue by gAmUssA** [Kong/docs.konghq.com#5381]
### Where is the problem?

https://docs.konghq.com/mesh/2.1.x/policies/meshopas

### What happened?

404 

### What did you expect to happen?

expected to see Mesh Policy for OPA

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by lahabana** [comment]
Like from the GUI. Maybe worth adding a redirects.

**Comment by lahabana** [comment]
https://docs.konghq.com/mesh/<anyVersion>/policies/meshopas to https://docs.konghq.com/mesh/<version>/features/meshopa/
