### ISSUE TITLE
Add port to KDS auth examples in Kong Mesh

### ISSUE THREAD

**Issue by Automaat** [Kong/docs.konghq.com#5413]
### Where is the problem?

https://docs.konghq.com/mesh/latest/features/kds-auth/

### What happened?

In [section about adding token](https://docs.konghq.com/mesh/latest/features/kds-auth/#add-token-to-each-zone-configuration), in Kubernetes example we have: 
```
kumactl install control-plane \
  --mode=zone \
  --zone=<zone name> \
  --cp-token-path=/tmp/token \
  --ingress-enabled \
  --kds-global-address grpcs://`<global-kds-address>` | kubectl apply -f -
```
it is missing port in kds address 

### What did you expect to happen?

This command should look like this: 
```
kumactl install control-plane \
  --mode=zone \
  --zone=<zone name> \
  --cp-token-path=/tmp/token \
  --ingress-enabled \
  --kds-global-address grpcs://`<global-kds-address>`: 5685 | kubectl apply -f -
```

Same problem is in universal example

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by slonka** [comment]
Reproduce:

```
curl -L https://docs.konghq.com/mesh/installer.sh | VERSION=0.0.0-preview.v5a7ccde48 sh -
```

**Comment by Automaat** [comment]
https://github.com/Kong/docs.konghq.com/pull/5426
