### ISSUE TITLE
google search "kong mesh rbac" returns 404 link

### ISSUE THREAD

**Issue by lobkovilya** [Kong/docs.konghq.com#5461]
### Where is the problem?

Not sure if this is the right place to report the issue, but the first link in google response for "kong mesh rbac" returns 404.
<img width="727" alt="Screenshot 2023-04-19 at 17 28 32" src="https://user-images.githubusercontent.com/12110261/233125891-e9b50d75-66ec-48f6-8a3e-a1fa7855c80d.png">

Link: https://docs.konghq.com/mesh/latest/production/secure-deployment/

### What is your suggestion?

The actual link should be https://docs.konghq.com/mesh/latest/production/secure-deployment/rbac/

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by fabianrbz** [comment]
@lobkovilya I believe that we fixed this, is this still an issue?

**Comment by lobkovilya** [comment]
Yes, it's fixed now, thanks 👍
