### ISSUE TITLE
"Install with Kong Gateway using Helm" sidebar has extra dead links.

### ISSUE THREAD

**Issue by eshih** [Kong/docs.konghq.com#5479]
### Where is the problem?

https://docs.konghq.com/gateway/3.2.x/install/kubernetes/helm-quickstart/#configure-kubectl

### What happened?

![Screen Shot 2023-04-24 at 11 51 10 AM](https://user-images.githubusercontent.com/1985999/234049847-17afb4fc-8d3f-4807-a669-6ae0b6fc241d.png)

The sidebar has extra tabs/sections that does not match the information listed in the page itself. Not sure if this page is missing documentation, or if the sidebar wasn't updated to match the page headers.

For Example, the `Kind Kubernetes`, `Create Kubernetes Cluster`, `Prepare the Helm Chart` sections are missing and the `Depencies` section is repeated multiple times. 

### What did you expect to happen?

The sidebar should match the headers of the documentation page. 

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by lena-larionova** [comment]
This was fixed in December, the doc is now https://docs.konghq.com/kubernetes-ingress-controller/latest/install/helm/
