### ISSUE TITLE
 "code repository documentation" url on the "Get Kong" page returns 404

### ISSUE THREAD

**Issue by AndyZhang0707** [Kong/docs.konghq.com#5539]
### Where is the problem?

https://docs.konghq.com/gateway/3.2.x/get-started/

### What happened?

The "code repository documentation" url (https://github.com/Kong/get.konghq.com) in the Note section returns 404.

### What did you expect to happen?

A valid URL should be provided and it should open a valid page.

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by lena-larionova** [comment]
Ah! Just saw your comment, and completely agree. I'll remove the URL.
