### ISSUE TITLE
Add "enterprise" badge in kong.websocket articles

### ISSUE THREAD

**Issue by kill-ka** [Kong/docs.konghq.com#5555]
### Where is the problem?

https://docs.konghq.com/gateway/3.2.x/plugin-development/pdk/kong.websocket.client

### What happened?

Howdy! Unlike [kong.jwe](https://docs.konghq.com/gateway/3.2.x/plugin-development/pdk/kong.jwe/) there is no "enterprise" badge for following articles: [kong.websocket.client](https://docs.konghq.com/gateway/3.2.x/plugin-development/pdk/kong.websocket.client), [kong.websocket.upstream](https://docs.konghq.com/gateway/3.2.x/plugin-development/pdk/kong.websocket.upstream/).

### What did you expect to happen?

Add an "enterprise" badge to avoid confusion for users.

### Code of Conduct and Community Expectations

- [x] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by riordanp** [comment]
bump, was shocked to find I cannot use this part of the sdk in my plugin. if you're going to kneecap kong's functionality for oss users then at least make a note in the documentation so people don't spend hours on an implementation that uses methods not available to them!
