### ISSUE TITLE
Transformation plugins missing documentation

### ISSUE THREAD

**Issue by rajeevkong** [Kong/docs.konghq.com#5593]
### Where is the problem?

https://docs.konghq.com/hub/kong-inc/request-transformer-advanced/configuration/

### What happened?

In the older document you could see that the headers could be added to the request transformation advanced plugin. The information also provided how customers can reference values stored in vaults like Hashicorp or AWS secrets manager.

### What did you expect to happen?

I expected to see documentation on how to set up referenced headers.

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by lena-larionova** [comment]
> In the older document you could see that the headers could be added to the request transformation advanced plugin. 

The doc that you're asking about is here: https://docs.konghq.com/hub/kong-inc/request-transformer-advanced/how-to/

> The information also provided how customers can reference values stored in vaults like Hashicorp or AWS secrets manager.

I believe this is the doc you're referring to: https://docs.konghq.com/hub/kong-inc/request-transformer-advanced/how-to/templates/

Both of these documents have links from the plugin landing page: https://docs.konghq.com/hub/kong-inc/request-transformer-advanced/#get-started-with-the-request-transformer-advanced-plugin

I understand the confusion with the link text, so I'll adjust that to be more descriptive of the contents of the page it's linking to.
