### ISSUE TITLE
Konnect Plugin Compatibility tables are empty

### ISSUE THREAD

**Issue by d19dotca** [Kong/docs.konghq.com#5606]
### Where is the problem?

https://docs.konghq.com/konnect/compatibility/#plugin-compatibility

### What happened?

This page has a section Plugin Compatibility which headers of what looks to be the start of tables, however there doesn't appear to be any data presented in them.

<img width="1011" alt="image" src="https://github.com/Kong/docs.konghq.com/assets/8153796/1fbd848b-6041-44eb-bed3-aff1f7343617">

### What did you expect to happen?

I expected to see a table of the Kong plugins which and the tiers at which they apply to Konnect Plus accounts (for example) on this documentation page. This can be also achieved though with the primary plugin hub page at https://docs.konghq.com/hub/ and selecting "tiers" dropdown.

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by lena-larionova** [comment]
Ack - on it. Missed validating this page.
