### ISSUE TITLE
Request Transformer Advanced plugin does not mention which fields are referenceable fields

### ISSUE THREAD

**Issue by mark-sivill-kong** [Kong/docs.konghq.com#5626]
### Where is the problem?

https://docs.konghq.com/hub/kong-inc/request-transformer-advanced/configuration/

### What happened?

The following fields do not mention that they are referenceable

- replace.headers
- replace.querystring
- replace.body
- rename.headers
- rename.querystring
- rename.body
- add.headers
- add.querystring
- add.body
- append.headers
- append.querystring
- append.body

### What did you expect to happen?

The fields that are referenceable are flagged in the docs.

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by lena-larionova** [comment]
Looks like we have an issue with generating some metadata for nested parameters.

@fabianrbz, can you take a look when you're back?
