### ISSUE TITLE
On OpenShfit page: remove Kubernetes requirements and put the OpenShift requirements

### ISSUE THREAD

**Issue by jeromeguillaume** [Kong/docs.konghq.com#5688]
### Where is the problem?

https://docs.konghq.com/gateway/latest/install/kubernetes/openshift/#prerequisites

### What happened?

On the OpenShfit page we found the Kubernetes requirements:
```
kubernetes cluster, v1.19 or later
kubectl v1.19 or later
```

### What did you expect to happen?

I would like to have OpenShift requirement:
```
An OpenShift cluster, v4 or later
OpenShift CLI `oc` v4 or later
```

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by Abhicodeitout** [comment]
@jeromeguillaume  i am not getting options to add label

**Comment by fabianrbz** [comment]
@Abhicodeitout @jeromeguillaume is this still an issue?

**Comment by jeromeguillaume** [comment]
No it was fixed.
