### ISSUE TITLE
instance_name listed on incorrect versions

### ISSUE THREAD

**Issue by rainest** [Kong/docs.konghq.com#5712]
### Where is the problem?

https://docs.konghq.com/gateway/3.1.x/admin-api/#add-plugin

### What happened?

`instance_name` is listed in the 3.1 admin API plugin reference. However, this field [was not added until 3.2](https://github.com/Kong/kong/commit/f7f5367f8615659bb24b14f6ab6d8f2d30f3e5af)

Compare to the equivalent docs for plugin pages: https://github.com/Kong/docs.konghq.com/blob/3b52051f57cf635ba405c9b59fe5b2c768e0f795/app/_includes/plugins/schema.html#L20-L35

See also:
https://github.com/Kong/kong/blame/master/kong/db/schema/entities/plugins.lua#L19
https://github.com/Kong/kong/blob/3.1.1/kong/db/schema/entities/plugins.lua

### What did you expect to happen?

`instance_name` is only listed on 3.2+

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by fabianrbz** [comment]
This issue has been fixed as part of https://github.com/Kong/docs.konghq.com/pull/5713
