### ISSUE TITLE
Specify that kong host names are case-sensitive.

### ISSUE THREAD

**Issue by kikito** [Kong/docs.konghq.com#586]
As illustrated in https://github.com/Kong/getkong.org/pull/456, users might be surprised when they create an API for "EXAMPLE.COM" and find out that it is not matched by a request for "example.com". We should indicate that the `host` param in APIs (and Routes and Services) is case-sensitive.

**Comment by james-callahan** [comment]
Rather: should we fix things so that they *aren't* case sensitive?
Relatedly, do we need to do any i18n normalization? (idna/punycode)

**Comment by falondarville** [comment]
Created a task for myself and I will note in the documentation that `host` is case sensitive.

**Comment by subnetmarco** [comment]
This doesn't comply with RFC 4343 https://datatracker.ietf.org/doc/html/rfc4343, and it should be case insensitive instead.
