### ISSUE TITLE
Kong Mesh Retry policy lists field that is not available

### ISSUE THREAD

**Issue by lnajdekKong** [Kong/docs.konghq.com#5913]
### Where is the problem?

https://docs.konghq.com/mesh/2.3.x/policies/retry/#http

### What happened?

Documentation references "baseDuration" in the http section. However, the field should be baseInterval. 

### What did you expect to happen?

Update the following to "baseInterval" instead of "baseDuration"
https://docs.konghq.com/mesh/2.3.x/policies/retry/#http

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by lahabana** [comment]
Done with https://github.com/kumahq/kuma-website/pull/1441 thx
