### ISSUE TITLE
Provide good and bad examples for API evaluation order

### ISSUE THREAD

**Issue by thibaultcha** [Kong/docs.konghq.com#611]
See https://github.com/Kong/kong/issues/3276

**Comment by prasad-marne** [comment]
I started working with kong recently and have found this particular area to be confusing. I would like to create PR to add proper docs regarding this issue. I think it will help people like me and any new users get better understanding of the evaluation order.

**Comment by falondarville** [comment]
We've opened a backlog task for this issue: DOCU-1572

**Comment by falondarville** [comment]
The latest documentation covers more specifics about regex paths in plainer language. Plus, it introduces the `regex_priority`  attribute. Please refer to https://docs.konghq.com/gateway-oss/2.5.x/proxy/#evaluation-order.
