### ISSUE TITLE
Adjust Mesh Manager diagram to reflect components under management

### ISSUE THREAD

**Issue by johnharris85** [Kong/docs.konghq.com#6180]
### Where is the problem?

https://docs.konghq.com/konnect/mesh-manager/

### What happened?

I just realized that in the main image, only the top global control plane should be in the "Kong Managed' box / border. 

### What did you expect to happen?

The zone cps and ingress/egress should be outside (customer managed). @cloudjumpercat do you have the original for this?

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by cloudjumpercat** [comment]
@johnharris85 Like this?

<img width="822" alt="Screenshot 2023-09-27 at 8 13 05 AM" src="https://github.com/Kong/docs.konghq.com/assets/75819066/301f69d5-daf4-4c56-a12b-24ec869425c4">

**Comment by johnharris85** [comment]
Perfect, thanks!
