### ISSUE TITLE
Update API version of `Gateway`s, `GatewayClass`es and `HTTPRoute`s to `gateway.networking.k8s.io/v1`

### ISSUE THREAD

**Issue by randmonkey** [Kong/docs.konghq.com#6352]
### Where is the problem?

https://docs.konghq.com/kubernetes-ingress-controller/latest/concepts/gateway-api/ and other related pages

### What happened?

Gateway API released `1.0.0-rc1` with promoting `Gateway`s, `GatewayClass`es and `HTTPRoute`s from `v1beta1` to `v1`. We need to update the example manifests to change the API version of these resources to `gateway.networking.k8s.io/v1`.

### What did you expect to happen?

APIVersion of all `Gateway`s, `GatewayClass`es and `HTTPRoute`s are updated to `gateway.networking.k8s.io/v1`

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by fabianrbz** [comment]
@randmonkey can we close this one?
