### ISSUE TITLE
[guide] Cassandra

### ISSUE THREAD

**Issue by subnetmarco** [Kong/docs.konghq.com#64]
We should write a little guide to install Cassandra.

**Comment by montanaflynn** [comment]
More importantly a multi-node setup guide. Installing Cassandra is pretty simple:

```
wget http://apache.mirrors.tds.net/cassandra/2.1.5/apache-cassandra-2.1.5-bin.tar.gz
tar xvzf apache-cassandra-2.1.5-bin.tar.gz
./apache-cassandra-2.1.5/bin/cassandra
```

**Comment by montanaflynn** [comment]
The guide to install Cassandra should probably cover installing Java as well

**Comment by thefosk** [comment]
+1 let's do it. @montanaflynn will you be able to take care of this? @jitachi can help if you need some UI

**Comment by ahmadnassri** [comment]
@thefosk @thibaultCha are we doing this? or should we close in light of PSQL and future no-db discussion?

**Comment by thefosk** [comment]
We will support Cassandra and Postgres because they serve different use-cases. This guide could have been useful when we only supported Cassandra, since we know also support Postgres maybe trying to use Kong is less of a pain. I would close.

**Comment by coopr** [comment]
@subnetmarco we have Cassandra installation described or referred to in some of the options on https://konghq.com/install/
