### ISSUE TITLE
Scrolling does not work on popups windows

### ISSUE THREAD

**Issue by jaikratsingh** [Kong/docs.konghq.com#6447]
### Where is the problem?

When you search anything in the search box and if the popup window size is longer than screen then while scrolling  instead of popup window the page behind the popup window start scrolling.  Cant attach the image due to company policy 
:(

### What is your suggestion?

Only popup window should scroll.  

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by lena-larionova** [comment]
This will be resolved with https://github.com/Kong/docs.konghq.com/pull/6377.
