### ISSUE TITLE
Add instructions for uploading OAS to Konnect Dev Portal

### ISSUE THREAD

**Issue by djjazzyjew** [Kong/docs.konghq.com#6604]
### Where is the problem?

https://docs.konghq.com/konnect/api-products/service-documentation/#api-specification

### What happened?

There aren't instructions to guide users to upload an OAS file to their API Product Version.  Instead it is buried in a page titled "Dev Portal Service Documentation".  This also needs to be updated to reflect the new naming of "API Products".

### What did you expect to happen?

The docs should reflect the current process of uploading an OAS file in the following page in API Products:
![image](https://github.com/Kong/docs.konghq.com/assets/79609915/262b8961-d5b1-45b2-9a27-4b5ee17a557b)

The page title should also be changed to "Dev Portal API Product Documentation"

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by lena-larionova** [comment]
Fixed in https://github.com/Kong/docs.konghq.com/pull/6616.
