### ISSUE TITLE
Demo-App discrepency between Kong Konnect Mesh and Kong Mesh documentation

### ISSUE THREAD

**Issue by eshih** [Kong/docs.konghq.com#6625]
### Where is the problem?

https://docs.konghq.com/konnect/mesh-manager/service-mesh/#install-a-demo-service

### What happened?

The demo-app provided in the Konnect documentation [0] is not the same application as the demo-app provided in the mesh documentation that is linked [1]. This is likely to cause confusion among users how to actually test your application

[0] https://docs.konghq.com/konnect/mesh-manager/service-mesh/#install-a-demo-service
[1] https://docs.konghq.com/mesh/latest/quickstart/kubernetes/

### What did you expect to happen?

The sample application should be the same if the Konnect docs are pointing to the Kong Mesh docs as an example of how to set up an application within the mesh.

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by cloudjumpercat** [comment]
Hi @eshih ! Thanks for submitting this feedback! I've created a PR (#8008 ) that fixes this issue. Thanks again!
