### ISSUE TITLE
Managed Identity seems to be failing for Azure Container Apps for secret manager integration

### ISSUE THREAD

**Issue by khaikong** [Kong/docs.konghq.com#7099]
### Where is the problem?

The current way to use Managed Identity didn't specify specific Azure products in the way to set  [Managed Identity] in Kong(https://docs.konghq.com/gateway/latest/kong-enterprise/secrets-management/backends/azure-key-vaults/#configure-azure-key-vaults). We have tested with Azure Container App and it seems like its not working for Azure Container apps.

From [lua-resty-azure](https://github.com/Kong/lua-resty-azure?tab=readme-ov-file#managed-identity-authentication) we only mentioned Managed Identity only being tested for Azure Instance(VM) or Azure Function App

### What is your suggestion?

Would be good to have a mention in the doc on what have been tested with Managed Identity here in the documentation.

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by lena-larionova** [comment]
@khaikong I can't access the link to salesforce that you provided. Is the doc update that needs to be added simply that:

"Secrets management via Azure Vault is supported on Azure Instance (VM) and the Azure Function App.
It is not currently supported on Azure Container App."

**Comment by khaikong** [comment]
@lena-larionova my bad. I fixed the link. It not supposed to be a salesforce link. 

> I can't access the link to salesforce that you provided. Is the doc update that needs to be added simply that:

>"Secrets management via Azure Vault is supported on Azure Instance (VM) and the Azure Function App.
It is not currently supported on Azure Container App."


Yes.
