### ISSUE TITLE
OpenID Connect link is broken

### ISSUE THREAD

**Issue by richiebrandnew** [Kong/docs.konghq.com#757]
https://docs.konghq.com/plugins/ee-openid-connect/

When you click on Detailed Documentation, it leads to an error 

- `getkong.org` url(s):

### Summary

SUMMARY_GOES_HERE

### Steps To Reproduce

1.
2.
3.
4.

### Additional Details

ADDITIONAL_DETAILS_GO_HERE

**Comment by darrenjennings** [comment]
Closed by #758
