### ISSUE TITLE
Cannot Download 3.0.2.0.rpm 

### ISSUE THREAD

**Issue by imurata** [Kong/docs.konghq.com#7619]
### Where is the problem?

https://docs.konghq.com/gateway/3.0.x/install/linux/rhel/

### What happened?

I tried to download 3.0.2.0.rpm for RHEL9.
```
curl -Lo kong-enterprise-edition-3.0.2.0.rpm $(rpm --eval https://packages.konghq.com/public/gateway-30/rpm/el/%{rhel}/%{_arch}/kong-enterprise-edition-3.0.2.0.el%{rhel}.%{_arch}.rpm)
```
But the download was failed due to 404.

### What did you expect to happen?

The correct URL is listed in the Documentation and the download is successful.

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by mheap** [comment]
Hey @imurata,

Kong Gateway 3.0 does not support RHEL9. Additionally, 3.0 is no longer supported by Kong. We recommend updating to at least version 3.4, ideally version 3.7.
