### ISSUE TITLE
Prerequisites for "Create a Dev Portal"

### ISSUE THREAD

**Issue by timodwhit** [Kong/docs.konghq.com#7709]
### Where is the problem?

https://docs.konghq.com/konnect/dev-portal/create-dev-portal/

### What happened?

The prerequisites here list "Configure an [authentication strategy](https://docs.konghq.com/konnect/dev-portal/applications/enable-app-reg/) if you plan to use one"

2 Problems with that: 
1) The prerequisites on the authentication strategy list "[An API product that is versioned and published to a Konnect Dev Portal](https://docs.konghq.com/konnect/dev-portal/publish-service)."
1) The "Next Steps" contain: "[Enable or Disable Application Registration for an API Product Version](https://docs.konghq.com/konnect/dev-portal/applications/enable-app-reg/)"

### What did you expect to happen?

It seems like the "Prerequisites" should be dropped on the Create a Dev Portal page, and should only be follow up steps.

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by Guaris** [comment]
PR to resolve this here https://github.com/Kong/docs.konghq.com/pull/7997
