### ISSUE TITLE
No longer use --konnect flag with deck

### ISSUE THREAD

**Issue by imurata** [Kong/docs.konghq.com#7950]
### Where is the problem?

https://docs.konghq.com/deck/latest/guides/konnect/

### What happened?

Documenatation shows 
> You can use decK commands such as ping, diff, or sync with --konnect flags to interact with Konnect.
> If you don’t pass a Konnect flag to decK, decK looks for a local Kong Gateway instance instead.

But this flag doesn't work now.
```sh
$ deck gateway ping --konnect
Error: unknown flag: --konnect
```

### What did you expect to happen?

> You can use decK commands such as ping, diff, or sync with --konnect flags to interact with Konnect.
> If you don’t pass a Konnect flag to decK, decK looks for a local Kong Gateway instance instead.

Delete the above text and add the following text in its place

> deck provides the following flags when interacting with Konnect.

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by lena-larionova** [comment]
@imurata Looks like the doc is a bit misleading. There is no `--konnect` flag, there are `--konnect-*` flags like `--konnect-token`, `--konnect-control-plane-name`, etc. So you need to pass one of those flags (usually `--konnect-token`). For example, I just tested with this:

```
deck gateway ping --konnect-token kpat_<my-pat>

Successfully Konnected to the Lenas Test Org 2 organization!
```

**Comment by imurata** [comment]
ah, it appears to have been misleading.
Understood.
Thank you!
