### ISSUE TITLE
add unreleased version of the docs for KGO

### ISSUE THREAD

**Issue by lahabana** [Kong/docs.konghq.com#8033]
### Where is the problem?

Currently KGO doesn't have a way to merge docs for features about to be released. This is troublesome to ship docs at the same time as code.

### What is your suggestion?

Other docs have a "dev" or "unreleased" version, KGO should have the same.

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by fabianrbz** [comment]
@lahabana KGO does have support for `dev` as the rest of the docs, adding `label: unreleased` to the corresponding version should do it.

**Comment by pmalek** [comment]
@programmer04 I believe your PR #8034 will fix this, right?
