### ISSUE TITLE
[KGO] Add docs for the `KonnectExtension` feature

### ISSUE THREAD

**Issue by mlavacca** [Kong/docs.konghq.com#8044]
### Where is the problem?

The `KonnectExtension` feature has been added to KGO. We need to create docs for it.

### What is your suggestion?

Create docs for the `KonnectExtension` feature.

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by lena-larionova** [comment]
Completed in https://github.com/Kong/docs.konghq.com/pull/8097.
