### ISSUE TITLE
fix nav logo href to konghq.com

### ISSUE THREAD

**Issue by hernando1** [Kong/docs.konghq.com#806]
### Summary
direct navbar logo to konghq.com

ADDITIONAL_DETAILS_GO_HERE
If a user clicks on the Kong logo on docs.konghq.com they should be directed to konghq.com
update nav.html file
Replace href for navbar brand with https://konghq.com

**Comment by catfishbluefish** [comment]
PR: https://github.com/Kong/docs.konghq.com/pull/809

**Comment by catfishbluefish** [comment]
PR Merged
