### ISSUE TITLE
Update support policy link on konnect/availability-stages/

### ISSUE THREAD

**Issue by TomKaweski** [Kong/docs.konghq.com#8142]
Please update the link to Kong's support and maintenance policy on https://docs.konghq.com/konnect/availability-stages/ , which currently links to our April 2021 version, to the version available at the evergreen URL  https://konghq.com/supportandmaintenancepolicy/

Here is the current text and link on the Docs website:

General availability
General availability, or GA, means that the software is released publicly and is supported according to Kong’s [support and maintenance policy](https://konghq.com/wp-content/uploads/2021/04/Kong-Support-and-Maintenance-Policy-16-April-2021.pdf). Generally available features usually have official documentation (as needed) and interfaces are stable.

If feature documentation doesn’t have a tech preview, alpha, or beta label, then the feature is generally available.

You can depend on GA features in production environments.

**Comment by Guaris** [comment]
@TomKaweski This change has been made! Let us know if you need anything else.
