### ISSUE TITLE
Update (and possibly restructure) Gateway API upgrade guide in KIC's docs

### ISSUE THREAD

**Issue by pmalek** [Kong/docs.konghq.com#8282]
### Where is the problem?

https://docs.konghq.com/kubernetes-ingress-controller/latest/upgrade/kic/#update-gateway-api-from-v10-to-v11

### What happened?

KIC supports Gateway API 1.2 as of KIC 3.4.

The guide at https://docs.konghq.com/kubernetes-ingress-controller/latest/upgrade/kic/#update-gateway-api-from-v10-to-v11 only mentioned how to upgrade from 1.0 to 1.1.

### What did you expect to happen?

Guide documenting how to upgrade from Gateway API 1.1 to 1.2

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by mlavacca** [comment]
Here are is upstream Gateway API v1.2 upgrade notes: https://gateway-api.sigs.k8s.io/guides/#v12-upgrade-notes
