### ISSUE TITLE
Broken Link on GUI authentication page

### ISSUE THREAD

**Issue by levfishdevfish** [Kong/docs.konghq.com#837]
"Getting Started with the Admin GUI" leads to 404
https://docs.konghq.com/enterprise/0.33-x/admin-gui/configuration/authentication/

**Comment by thalaeg** [comment]
I will take care of this one!

**Comment by thalaeg** [comment]
It seems like this one is already fixed.

**Comment by coopr** [comment]
Whoops, yep, thanks @thalaeg !
