### ISSUE TITLE
Some Parameter Descriptions not showing up

### ISSUE THREAD

**Issue by john-paul-keenan** [Kong/docs.konghq.com#840]
- `docs.konghq.com` url(s): https://docs.konghq.com/enterprise/0.33-x/plugins/http-proxy-caching/

### Summary

If you go to the page listed above and scroll down to these paramaters, `config.storage_ttl` or `config.strategy` you'll notice they do not have a description. I was going to comb through the code to find it there, but I realized that in the raw markdown file, those were both described. For some reason, it's just not showing afyer the markdown is rendered. 

### Steps To Reproduce

1. Go to [this page](https://docs.konghq.com/enterprise/0.33-x/plugins/http-proxy-caching/)
2. Scroll down to `config.storage_ttl` or `config.strategy` 
3. Compare it to the raw version of [this file](https://github.com/Kong/docs.konghq.com-private/blob/a5cace70f7b3c3670e3031d5f2150cb39ccb0dd1/app/enterprise/0.32-x/plugins/http-proxy-caching.md)

**Comment by coopr** [comment]
Closed with https://github.com/Kong/docs.konghq.com/pull/841
