### ISSUE TITLE
ACL plugin documentation does not cover all endpoints

### ISSUE THREAD

**Issue by rahimimo** [Kong/docs.konghq.com#855]
- `docs.konghq.com` url(s):
 https://docs.konghq.com/plugins/acl/?_ga=2.3770608.1107935639.1537175982-1471612363.1530627052

### Summary

Documentations with plugins do not contain all the required information. For instance, disassociating a consumer from an ACL which is done as such
` curl -X DELETE http://localhost:8001/consumers/{consumer_id}/acls/{acl_id}`
is not there. 

### Additional Details

Unlike the other parts of docs the plugins' docs do not keep the versioning.

**Comment by coopr** [comment]
Hi @rahimimo thanks for reporting this. We welcome PRs to improve Kong documentation. We've recently launched Kong Hub https://konghq.com/blog/welcome-to-the-new-kong-hub/ so you'd want to edit https://github.com/Kong/docs.konghq.com/blob/master/app/_hub/kong-inc/acl/index.md

**Comment by falondarville** [comment]
I've created task DOCU-1575 to address this.

**Comment by falondarville** [comment]
The ACL plugin docs have been updated.
