### ISSUE TITLE
Cookie "dialog" is overlapped by "Kong Inc"

### ISSUE THREAD

**Issue by coopr** [Kong/docs.konghq.com#856]
https://docs.konghq.com/hub/

### Summary

The string "Kong Inc." overlaps the cookie warning.

### Steps To Reproduce

1. Visit https://docs.konghq.com/hub/ (in an incognito window, to force the cookie "dialog" to appear in the bottom right)
2. Scroll up and down
3. Notice that "Kong Inc." is "above" the cookie dialog

### Additional Details

Appears in both Chrome and Firefox on Mac OSX

![cookie and kong](https://user-images.githubusercontent.com/94904/45644351-6a76aa80-ba72-11e8-8814-423c44786759.gif)

**Comment by leevye** [comment]
https://github.com/Kong/docs.konghq.com/pull/862
