### ISSUE TITLE
When viewing a not-latest version of an extension, the extension's detail page should show warning and link

### ISSUE THREAD

**Issue by coopr** [Kong/docs.konghq.com#893]
In Kong CE and EE documentation, when you are viewing docs for a not-current version of Kong, you see a warning at the top of the page like:

![](https://user-images.githubusercontent.com/94904/45048756-9422e100-b031-11e8-8823-a79cd1be2701.jpg)

Kong Catalog docs pages should show the same sort of thing:

![](https://user-images.githubusercontent.com/94904/45048820-b452a000-b031-11e8-88ae-51da6cf59c63.jpg)

**Comment by falondarville** [comment]
Kong Catalog is deprecated.
