### ISSUE TITLE
Correctly capitalize Hub page titles

### ISSUE THREAD

**Issue by coopr** [Kong/docs.konghq.com#902]
### Summary

Visible on https://docs.konghq.com/hub/kong-inc/udp-log/ and other pages.

The page title is incorrectly capitalized.

![udp_log_plugin___kong_and_slack_-_kong](https://user-images.githubusercontent.com/94904/46031675-679d3a80-c0ae-11e8-9990-4bbce66c81d4.jpg)

As part of resolving this issue, page titles across other sections of https://docs.konghq.com/ should be checked.

**Comment by wshirey** [comment]
I randomly selected a couple of pages other than the affected pages (UDP, JWT and HMAC come to mind) and compared to docs.konghq.com and they were the same.

**Comment by wshirey** [comment]
@coopr Hmm noticing that this doesn't work for OAuth (rendered as Oauth) and StatsD (rendered as Statds). Wondering if there needs to be conditional logic to use verbatim text for certain pages?

**Comment by coopr** [comment]
The extensions in the Hub each have a `name: ` element - can we use that verbatim for titles on all pages? I think that'd keep things simple!
