### ISSUE TITLE
Bring back the "permalink icon" on hover over title in Hub

### ISSUE THREAD

**Issue by coopr** [Kong/docs.konghq.com#904]
### Summary

On most of https://docs.konghq.com/, hovering your cursor over any section title will make a permalink anchor appear next to that title. Clicking on it allows one to copy/paste the anchor link in a chat somewhere, which is very efficient to link a specific section of the docs.

![5-minute_quickstart_-_v0_14_x___kong_-_open-source_api_management_and_microservice_management](https://user-images.githubusercontent.com/94904/46047303-78af7100-c0d9-11e8-99fc-ecb8458f78f0.jpg)

In the Hub, this feature seems to be non-existent. Hovering over a title on a plugin's page does not do anything, making it hard to produce anchor links for plugins (e.g. link to the table of configuration option for that plugin). 

### Steps To Reproduce

Invalid:

1. Go to https://docs.konghq.com/hub/kong-inc/basic-auth/
2. Hover your cursor over "Terminology"
3. Nothing happens

Valid:

1. Go to https://docs.konghq.com/0.14.x/cli/#kong-check
2. Hover your cursor over any section title
3. Permalink icon appears left of that title

**Comment by thalaeg** [comment]
I will take care of this for all the section titles!
