### ISSUE TITLE
Make numbered list styling consistent

### ISSUE THREAD

**Issue by coopr** [Kong/docs.konghq.com#914]
On https://docs.konghq.com/hub/optum/kong-upstream-jwt/ the numbered list looks great:

![kong_upstream_jwt_plugin___kong](https://user-images.githubusercontent.com/94904/46113124-fccd2b80-c1a1-11e8-9623-aae7d490660e.jpg)

But on another page on the docs site https://docs.konghq.com/0.14.x/auth/, a list with the same HTML formatting doesn't look as good:

![authentication_reference_-_v0_14_x___kong_-_open-source_api_management_and_microservice_management](https://user-images.githubusercontent.com/94904/46113262-8250db80-c1a2-11e8-9fa0-555bbd979869.jpg)

**Comment by danimart1991** [comment]
I try to resolve this. What style do you want, the first or the second one?

**Comment by coopr** [comment]
The first one - I think it "looks great" while the second one "doesn't look as good" :)

**Comment by danimart1991** [comment]
Fixed. 😉
