### ISSUE TITLE
All pages should correctly render both unordered lists AND download buttons

### ISSUE THREAD

**Issue by coopr** [Kong/docs.konghq.com#917]
Currently the pages under /install (all the pages linked to from the buttons on https://konghq.com/install/) have special handling for Markdown unordered lists - if you edit a page like https://github.com/Kong/docs.konghq.com/blob/master/app/install/kubernetes.md to add an unordered list without links:

```
## Table of Contents

- foo
- bar
- bang
```

It will be rendered strangely:

![install_-_kong_on_kubernetes___kong_-_open-source_api_management_and_microservice_management](https://user-images.githubusercontent.com/94904/46363884-18648600-c629-11e8-9dcf-1f5ab14d5ba5.jpg)

and if you make the unordered list contain links:

```
## Table of Contents

- [foo](http://www.konghq.com)
- [bar](http://www.konghq.com)
- [bang](http://www.konghq.com)
```

it will be rendered as download buttons:

![install_-_kong_on_kubernetes___kong_-_open-source_api_management_and_microservice_management](https://user-images.githubusercontent.com/94904/46363931-43e77080-c629-11e8-8585-c29224e60a85.jpg)

Note that entering the same unordered list Markdown on pages outside of `/install` works as expected, and renders correctly as an unordered list.

To resolve this issue, we need a way to have a choice of showing download buttons, or unordered lists, on all pages in the site - note that this approach not only allows display of unordered lists on `/install` pages, but it also allows inclusion of download buttons on pages that are not in `/install`

### Suggested Resolution

There seem to be various options to resolve this https://stackoverflow.com/questions/40688633/how-can-i-add-a-button-in-a-md-file-with-jekyll - I think I prefer option 2, and I like https://stackoverflow.com/a/40753294

**Comment by john-paul-keenan** [comment]
@coopr I think I did what you wantted in https://github.com/Kong/docs.konghq.com/pull/918 but would appreciate it if others could review for me

**Comment by coopr** [comment]
I did an ugly hack to make https://docs.konghq.com/install/kubernetes/ display a Table of Contents - I used an ordered list:

![install_-_kong_on_kubernetes___kong_-_open-source_api_management_and_microservice_management](https://user-images.githubusercontent.com/94904/47529466-bc260800-d85c-11e8-8b3c-3eccd6a75052.jpg)
