### ISSUE TITLE
Document missing 'regex_priority' Route attribute

### ISSUE THREAD

**Issue by thibaultcha** [Kong/docs.konghq.com#931]
The `regex_priority` attributed added to the Route entity in Kong 0.13.0 is only documented in the [Proxy Guide](https://docs.konghq.com/0.14.x/proxy/#evaluation-order), but not in the [Admin API docs](https://docs.konghq.com/0.14.x/admin-api/#add-route) (there are no mentions of this field in the Route entity attributes).

This field should be documented for both Kong 0.13 and 0.14, hence, in both versions of the Admin API docs.

This issue was initially reported in https://discuss.konghq.com/t/kong-matching-priority/2062

**Comment by michizhou** [comment]
@thibaultcha If you don't mind, I would love to resolve this issue!

**Comment by thibaultcha** [comment]
@michizhou Sure! Thank you for the patch!
