### ISSUE TITLE
Add test to prevent bold formatting from being used in headers

### ISSUE THREAD

**Issue by coopr** [Kong/docs.konghq.com#934]
In many places in the docs there is bold formatted text in headers `### **Foo Bar**` - like here https://github.com/Kong/docs.konghq.com/blob/master/app/0.10.x/cli.md#kong-check (switch to raw view to see `#### **kong check**`)

The bold formatting is redundant (because headers will be bolded as necessary by CSS styling) and the bold formatting can cause problems with other functionality (see https://github.com/Kong/docs.konghq.com/pull/920#issuecomment-428736283 for an example of bolded headers causing auto-generated Table of Contents to have odd formatting)

The desired solution includes:

1. Find and remove all bold formatting in headers
1. Add linting/test to reject future additions of bold-formatted headers

Probably this should consider other header formatting we don't want - italics, underlined, etc.

**Comment by coopr** [comment]
I _think_ https://github.com/Kong/docs.konghq.com/pull/920/commits/75a70fd4df06b8d8c27f27358a73d145d6852e3c removes all bold formatting from headers.

**Comment by viragumathe5** [comment]
Shall I contribute to this issue????

**Comment by viragumathe5** [comment]
I mean is this issue still open

**Comment by Aswinpookkatt** [comment]
Is issue still open?
