### ISSUE TITLE
Handle heading levels 5 and beyond correctly - or prevent them from being used

### ISSUE THREAD

**Issue by coopr** [Kong/docs.konghq.com#942]
As pointed out in https://github.com/Kong/docs.konghq.com/pull/920#issuecomment-429495419 the current automatic Table of Contents (ToC) generator doesn't handle Heading level 5 and beyond correctly.

Either we should correctly handle such headings, or we should prevent them from being used by checking for them in our testing/linting phase.

**Comment by hutchic** [comment]
As a proposed workaround we could also just not display TOC items that are beyond 5 levels deep.

**Comment by coopr** [comment]
I think that is a reasonable approach @hutchic - a PR is welcome!

**Comment by coopr** [comment]
Ah @allejo you are the best, thanks!
