### ISSUE TITLE
Fix mis-ordered headings in older docs

### ISSUE THREAD

**Issue by coopr** [Kong/docs.konghq.com#944]
### Summary

Our new automatic Table of Contents feature depends on well-ordered headings (H1 -> H2 -> H3, etc) - mis-ordered headings (H1 -> H2 -> H4) cause the ToC to render poorly.

### Steps To Reproduce

1. Visit https://docs.konghq.com/0.13.x/clustering/
2. Notice how the table of contents at the top is malformed
3. Visit the source for that page https://raw.githubusercontent.com/Kong/docs.konghq.com/master/app/0.13.x/clustering.md
4. Notice how the first heading is `#` (H1) and the second heading is `###` (H3) - H2 has been skipped

### Additional Details

#920 included fixes for headings for the current Kong versions (Kong 0.14 and Kong Enterprise 0.33) - older Kong versions have not had their headings reviewed and corrected.

**Comment by coopr** [comment]
This will most likely take LOTS of manual review and adjustments, unless someone can figure out a clever automated editing process.

**Comment by cfreksen** [comment]
I am looking into writing an one-off script to fix this.

**Comment by coopr** [comment]
Here are some suggestions if you plan to contribute to solving this issue:

- Work on one "version" of the docs at a time - working from most recent to older. Kong 0.14 and Kong Enterprise 0.33 docs have already had their heading orders reviewed and corrected. The next most-popular section of docs that could be reviewed and corrected is [Kong 0.13](https://github.com/Kong/docs.konghq.com/tree/master/app/0.13.x), followed by [Kong Enterprise 0.32](https://github.com/Kong/docs.konghq.com/tree/master/app/enterprise/0.32-x), and so on. 
- You'll need to run the docs site locally and preview your changes as you go - trying to do this without preview will be tricky

**Comment by cfreksen** [comment]
I know you have already processed the documentation for the current version, but I think I have found a few issues in it:
Look at `Plugin Object` in the TOC in https://docs.konghq.com/0.14.x/admin-api/
- Should `Precedence` and `Request Querystring Parameters` be changed, so their level is only 1 deeper than their parent?
- Should `Retrieve Plugin` be a subheading/child of `Plugin Object` rather than a sibling?

**Comment by coopr** [comment]
> I know you have already processed the documentation for the current version, but I think I have found a few issues in it:
> Look at `Plugin Object` in the TOC in https://docs.konghq.com/0.14.x/admin-api/
> 
> * Should `Precedence` and `Request Querystring Parameters` be changed, so their level is only 1 deeper than their parent?
> * Should `Retrieve Plugin` be a subheading/child of `Plugin Object` rather than a sibling?

Good catch! Clearly, I wasn't paying close enough attention while tuning-up that doc.

> Similarly, there are some issues in Plugin Development documents, e.g. https://docs.konghq.com/0.14.x/plugin-development/entities-cache/

Ah, right you are there as well! Thanks for keeping close 👀 on this - your further fixes are welcome!
