### ISSUE TITLE
Make Kong 1.0 version number work correctly

### ISSUE THREAD

**Issue by coopr** [Kong/docs.konghq.com#947]
https://github.com/Kong/docs.konghq.com/pull/946 demonstrated that using `1.0` for a Kong version number causes the Docs site to build incorrectly. 

`1.0.x` works correctly, but we don't want to use the trailing `.x` once we release Kong 1.0

**Comment by dash34** [comment]
I would like to work on this issue. How can i start?

**Comment by coopr** [comment]
I'd suggest you pull #946 , get it running locally, then try to fix the issue.

**Comment by coopr** [comment]
@dash34 we got this fixed, just letting you know.
