### ISSUE TITLE
Heading level CSS needs correction for H2 and H3

### ISSUE THREAD

**Issue by coopr** [Kong/docs.konghq.com#993]
### Summary

H2 and H3 are currently visually indistinguishable:

![basic_authentication_plugin___kong](https://user-images.githubusercontent.com/94904/47527772-3acc7680-d858-11e8-8bc8-ef0e1cd497e5.jpg)

### Steps To Reproduce

1. Visit https://docs.konghq.com/hub/kong-inc/basic-auth/
2. Inspect some headers - you'll notice that some of the have the same size+style, but are different heading levels

Note that this issue is apparent throughout the docs site, not just in the Hub.

**Comment by knrt10** [comment]
@coopr I would like to work on this.

**Comment by coopr** [comment]
Thanks @TheTechZone much appreciated!

**Comment by coopr** [comment]
Hmm, strange, this still seems to be broken - on https://docs.konghq.com/hub/kong-inc/basic-auth/ H2 and H3 appear to be the same:

![basic_authentication_plugin___kong](https://user-images.githubusercontent.com/94904/47886746-30caea80-ddf9-11e8-9960-c9f45f601a45.jpg)

**Comment by polarweasel** [comment]
It's inheriting that on line 37 of `/app/_assets/stylesheets/pages/extension.less`:

```css
.page-extension-profile {
  .content {

...

    h2 {
      font-size: 26px;
      margin: 20px 0;
    }
```

I have _no idea_ where all that definition might feed into, but it's definitely where that particular heading is getting its font size.

Using the web inspector in Firefox, overriding to turn that particular property off solves the problem.

**Default:**
<img width="358" alt="screen shot 2018-11-14 at 17 14 34" src="https://user-images.githubusercontent.com/538384/48523335-e00fb480-e830-11e8-9fe2-512369fde072.png">

**Overriding the 26px setting:**
<img width="361" alt="screen shot 2018-11-14 at 17 14 46" src="https://user-images.githubusercontent.com/538384/48523336-e00fb480-e830-11e8-8fdc-d54e95e9748d.png">

**Comment by polarweasel** [comment]
Hmm. My change here is the same as TechZone’s. Did that one not get merged into the Kong repo? It sorta looks like it only got merged into TechZone’s fork... No wonder the change didn’t propagate. :)

**Comment by polarweasel** [comment]
(Comment thread continued on my pull request #1044 if you’re wondering why the silence here...)
